

GO
PRINT N'Dropping [dbo].[DF_PK_EDI204SummaryHeader_DateEntered]...';


GO
ALTER TABLE [dbo].[EDI204SummaryHeader] DROP CONSTRAINT [DF_PK_EDI204SummaryHeader_DateEntered];


GO
PRINT N'Starting rebuilding table [dbo].[EDI204SummaryHeader]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_EDI204SummaryHeader] (
    [eshHeaderID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [eshTradingPartner]              VARCHAR (20)    NULL,
    [eshGroupControlNo]              BIGINT          NULL,
    [eshBOLNo]                       VARCHAR (30)    NULL,
    [eshMasterBOLNo]                 VARCHAR (30)    NULL,
    [eshMethodOfPayment]             VARCHAR (10)    NULL,
    [eshSetPurpose]                  VARCHAR (10)    NULL,
    [eshCustomerReferenceNo]         VARCHAR (30)    NULL,
    [eshLocationId]                  VARCHAR (30)    NULL,
    [eshShipDescription]             VARCHAR (30)    NULL,
    [eshOrderType]                   VARCHAR (30)    NULL,
    [eshPurchaseOrderNo]             VARCHAR (30)    NULL,
    [eshLocationNumber]              VARCHAR (30)    NULL,
    [eshShipDate]                    DATETIME2 (7)   NULL,
    [eshArrivalDate3PL]              DATETIME2 (7)   NULL,
    [eshServiceMode]                 NVARCHAR (30)   NULL,
    [eshProductType]                 NVARCHAR (30)   NULL,
    [eshLatitude]                    VARCHAR (30)    NULL,
    [eshLongitude]                   VARCHAR (30)    NULL,
    [eshReasonCodeCancellation]      VARCHAR (30)    NULL,
    [eshManifestNo]                  VARCHAR (30)    NULL,
    [eshTotalWeight]                 DECIMAL (18, 2) NULL,
    [eshTotalCubicFeet]              DECIMAL (18, 2) NULL,
    [eshTotalPieces]                 BIGINT          NULL,
    [eshDeliveryCommitmentType]      VARCHAR (30)    NULL,
    [eshScheduledPickupDate]         DATETIME2 (7)   NULL,
    [eshScheduledDeliveryDate]       DATETIME2 (7)   NULL,
    [eshSpecialNotes]                VARCHAR (30)    NULL,
    [eshConsigneeName]               VARCHAR (60)    NULL,
    [eshConsigneeNameID]             BIGINT          NULL,
    [eshConsigneeAddress1]           VARCHAR (75)    NULL,
    [eshConsigneeAddress2]           VARCHAR (75)    NULL,
    [eshConsigneeCity]               VARCHAR (75)    NULL,
    [eshConsigneeState]              VARCHAR (25)    NULL,
    [eshConsigneePostalCode]         VARCHAR (15)    NULL,
    [eshConsigneeCountryCode]        VARCHAR (10)    NULL,
    [eshConsigneeContactName]        VARCHAR (75)    NULL,
    [eshConsigneeContactNumber]      VARCHAR (80)    NULL,
    [eshConsigneeAltContName]        VARCHAR (75)    NULL,
    [eshConsigneeAltContNumber]      VARCHAR (80)    NULL,
    [eshInterConsigneeName]          VARCHAR (60)    NULL,
    [eshInterConsigneeNameID]        BIGINT          NULL,
    [eshInterConsigneeAddress1]      VARCHAR (75)    NULL,
    [eshInterConsigneeAddress2]      VARCHAR (75)    NULL,
    [eshInterConsigneeCity]          VARCHAR (75)    NULL,
    [eshInterConsigneeState]         VARCHAR (25)    NULL,
    [eshInterConsigneePostalCode]    VARCHAR (15)    NULL,
    [eshInterConsigneeCountryCode]   VARCHAR (10)    NULL,
    [eshInterConsigneeContactName]   VARCHAR (75)    NULL,
    [eshInterConsigneeContactNumber] VARCHAR (80)    NULL,
    [eshInterConsigneeAltContName]   VARCHAR (75)    NULL,
    [eshInterConsigneeAltContNumber] VARCHAR (80)    NULL,
    [eshShipFromName]                VARCHAR (60)    NULL,
    [eshShipFromNameID]              BIGINT          NULL,
    [eshShipFromAddress1]            VARCHAR (75)    NULL,
    [eshShipFromAddress2]            VARCHAR (75)    NULL,
    [eshShipFromCity]                VARCHAR (75)    NULL,
    [eshShipFromState]               VARCHAR (25)    NULL,
    [eshShipFromPostalCode]          VARCHAR (15)    NULL,
    [eshShipFromCountryCode]         VARCHAR (10)    NULL,
    [eshShipFromContactName]         VARCHAR (75)    NULL,
    [eshShipFromContactNumber]       VARCHAR (80)    NULL,
    [eshShipFromAltContName]         VARCHAR (75)    NULL,
    [eshShipFromAltContNumber]       VARCHAR (80)    NULL,
    [eshBillToName]                  VARCHAR (60)    NULL,
    [eshBillToNameID]                BIGINT          NULL,
    [eshBillToAddress1]              VARCHAR (75)    NULL,
    [eshBillToAddress2]              VARCHAR (75)    NULL,
    [eshBillToCity]                  VARCHAR (75)    NULL,
    [eshBillToState]                 VARCHAR (25)    NULL,
    [eshBillToPostalCode]            VARCHAR (15)    NULL,
    [eshBillToCountryCode]           VARCHAR (10)    NULL,
    [eshBillToContactName]           VARCHAR (75)    NULL,
    [eshBillToContactNumber]         VARCHAR (80)    NULL,
    [eshBillToAltContName]           VARCHAR (75)    NULL,
    [eshBillToAltContNumber]         VARCHAR (80)    NULL,
    [eshTextData]                    VARCHAR (MAX)   NULL,
    [eshUDF01]                       VARCHAR (30)    NULL,
    [eshUDF02]                       VARCHAR (30)    NULL,
    [eshUDF03]                       VARCHAR (30)    NULL,
    [eshUDF04]                       VARCHAR (30)    NULL,
    [eshUDF05]                       VARCHAR (30)    NULL,
    [eshUDF06]                       VARCHAR (30)    NULL,
    [eshUDF07]                       VARCHAR (30)    NULL,
    [eshUDF08]                       VARCHAR (30)    NULL,
    [eshUDF09]                       VARCHAR (30)    NULL,
    [eshUDF10]                       VARCHAR (30)    NULL,
    [ProFlags01]                     VARCHAR (1)     NULL,
    [ProFlags02]                     VARCHAR (1)     NULL,
    [ProFlags03]                     VARCHAR (1)     NULL,
    [ProFlags04]                     VARCHAR (1)     NULL,
    [ProFlags05]                     VARCHAR (1)     NULL,
    [ProFlags06]                     VARCHAR (1)     NULL,
    [ProFlags07]                     VARCHAR (1)     NULL,
    [ProFlags08]                     VARCHAR (1)     NULL,
    [ProFlags09]                     VARCHAR (1)     NULL,
    [ProFlags10]                     VARCHAR (1)     NULL,
    [ProFlags11]                     VARCHAR (1)     NULL,
    [ProFlags12]                     VARCHAR (1)     NULL,
    [ProFlags13]                     VARCHAR (1)     NULL,
    [ProFlags14]                     VARCHAR (1)     NULL,
    [ProFlags15]                     VARCHAR (1)     NULL,
    [ProFlags16]                     VARCHAR (1)     NULL,
    [ProFlags17]                     VARCHAR (1)     NULL,
    [ProFlags18]                     VARCHAR (1)     NULL,
    [ProFlags19]                     VARCHAR (1)     NULL,
    [ProFlags20]                     VARCHAR (1)     NULL,
    [DateEntered]                    DATETIME2 (7)   CONSTRAINT [DF_PK_EDI204SummaryHeader_DateEntered] DEFAULT (getutcdate()) NULL,
    [EnteredBy]                      VARCHAR (50)    NULL,
    [DateChanged]                    DATETIME2 (7)   NULL,
    [ChangedBy]                      VARCHAR (50)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_EDI204SummaryHeader1] PRIMARY KEY CLUSTERED ([eshHeaderID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[EDI204SummaryHeader])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_EDI204SummaryHeader] ON;
        INSERT INTO [dbo].[tmp_ms_xx_EDI204SummaryHeader] ([eshHeaderID], [eshTradingPartner], [eshGroupControlNo], [eshBOLNo], [eshMasterBOLNo], [eshMethodOfPayment], [eshSetPurpose], [eshCustomerReferenceNo], [eshLocationId], [eshShipDescription], [eshOrderType], [eshPurchaseOrderNo], [eshLocationNumber], [eshShipDate], [eshArrivalDate3PL], [eshProductType], [eshLatitude], [eshLongitude], [eshReasonCodeCancellation], [eshManifestNo], [eshTotalWeight], [eshTotalCubicFeet], [eshTotalPieces], [eshDeliveryCommitmentType], [eshScheduledPickupDate], [eshScheduledDeliveryDate], [eshSpecialNotes], [eshConsigneeName], [eshConsigneeNameID], [eshConsigneeAddress1], [eshConsigneeAddress2], [eshConsigneeCity], [eshConsigneeState], [eshConsigneePostalCode], [eshConsigneeCountryCode], [eshConsigneeContactName], [eshConsigneeContactNumber], [eshConsigneeAltContName], [eshConsigneeAltContNumber], [eshInterConsigneeName], [eshInterConsigneeNameID], [eshInterConsigneeAddress1], [eshInterConsigneeAddress2], [eshInterConsigneeCity], [eshInterConsigneeState], [eshInterConsigneePostalCode], [eshInterConsigneeCountryCode], [eshInterConsigneeContactName], [eshInterConsigneeContactNumber], [eshInterConsigneeAltContName], [eshInterConsigneeAltContNumber], [eshShipFromName], [eshShipFromNameID], [eshShipFromAddress1], [eshShipFromAddress2], [eshShipFromCity], [eshShipFromState], [eshShipFromPostalCode], [eshShipFromCountryCode], [eshShipFromContactName], [eshShipFromContactNumber], [eshShipFromAltContName], [eshShipFromAltContNumber], [eshBillToName], [eshBillToNameID], [eshBillToAddress1], [eshBillToAddress2], [eshBillToCity], [eshBillToState], [eshBillToPostalCode], [eshBillToCountryCode], [eshBillToContactName], [eshBillToContactNumber], [eshBillToAltContName], [eshBillToAltContNumber], [eshTextData], [eshUDF01], [eshUDF02], [eshUDF03], [eshUDF04], [eshUDF05], [eshUDF06], [eshUDF07], [eshUDF08], [eshUDF09], [eshUDF10], [ProFlags01], [ProFlags02], [ProFlags03], [ProFlags04], [ProFlags05], [ProFlags06], [ProFlags07], [ProFlags08], [ProFlags09], [ProFlags10], [ProFlags11], [ProFlags12], [ProFlags13], [ProFlags14], [ProFlags15], [ProFlags16], [ProFlags17], [ProFlags18], [ProFlags19], [ProFlags20], [DateEntered], [EnteredBy], [DateChanged], [ChangedBy])
        SELECT   [eshHeaderID],
                 [eshTradingPartner],
                 [eshGroupControlNo],
                 [eshBOLNo],
                 [eshMasterBOLNo],
                 [eshMethodOfPayment],
                 [eshSetPurpose],
                 [eshCustomerReferenceNo],
                 [eshLocationId],
                 [eshShipDescription],
                 [eshOrderType],
                 [eshPurchaseOrderNo],
                 [eshLocationNumber],
                 [eshShipDate],
                 [eshArrivalDate3PL],
                 [eshProductType],
                 [eshLatitude],
                 [eshLongitude],
                 [eshReasonCodeCancellation],
                 [eshManifestNo],
                 [eshTotalWeight],
                 [eshTotalCubicFeet],
                 [eshTotalPieces],
                 [eshDeliveryCommitmentType],
                 [eshScheduledPickupDate],
                 [eshScheduledDeliveryDate],
                 [eshSpecialNotes],
                 [eshConsigneeName],
                 [eshConsigneeNameID],
                 [eshConsigneeAddress1],
                 [eshConsigneeAddress2],
                 [eshConsigneeCity],
                 [eshConsigneeState],
                 [eshConsigneePostalCode],
                 [eshConsigneeCountryCode],
                 [eshConsigneeContactName],
                 [eshConsigneeContactNumber],
                 [eshConsigneeAltContName],
                 [eshConsigneeAltContNumber],
                 [eshInterConsigneeName],
                 [eshInterConsigneeNameID],
                 [eshInterConsigneeAddress1],
                 [eshInterConsigneeAddress2],
                 [eshInterConsigneeCity],
                 [eshInterConsigneeState],
                 [eshInterConsigneePostalCode],
                 [eshInterConsigneeCountryCode],
                 [eshInterConsigneeContactName],
                 [eshInterConsigneeContactNumber],
                 [eshInterConsigneeAltContName],
                 [eshInterConsigneeAltContNumber],
                 [eshShipFromName],
                 [eshShipFromNameID],
                 [eshShipFromAddress1],
                 [eshShipFromAddress2],
                 [eshShipFromCity],
                 [eshShipFromState],
                 [eshShipFromPostalCode],
                 [eshShipFromCountryCode],
                 [eshShipFromContactName],
                 [eshShipFromContactNumber],
                 [eshShipFromAltContName],
                 [eshShipFromAltContNumber],
                 [eshBillToName],
                 [eshBillToNameID],
                 [eshBillToAddress1],
                 [eshBillToAddress2],
                 [eshBillToCity],
                 [eshBillToState],
                 [eshBillToPostalCode],
                 [eshBillToCountryCode],
                 [eshBillToContactName],
                 [eshBillToContactNumber],
                 [eshBillToAltContName],
                 [eshBillToAltContNumber],
                 [eshTextData],
                 [eshUDF01],
                 [eshUDF02],
                 [eshUDF03],
                 [eshUDF04],
                 [eshUDF05],
                 [eshUDF06],
                 [eshUDF07],
                 [eshUDF08],
                 [eshUDF09],
                 [eshUDF10],
                 [ProFlags01],
                 [ProFlags02],
                 [ProFlags03],
                 [ProFlags04],
                 [ProFlags05],
                 [ProFlags06],
                 [ProFlags07],
                 [ProFlags08],
                 [ProFlags09],
                 [ProFlags10],
                 [ProFlags11],
                 [ProFlags12],
                 [ProFlags13],
                 [ProFlags14],
                 [ProFlags15],
                 [ProFlags16],
                 [ProFlags17],
                 [ProFlags18],
                 [ProFlags19],
                 [ProFlags20],
                 [DateEntered],
                 [EnteredBy],
                 [DateChanged],
                 [ChangedBy]
        FROM     [dbo].[EDI204SummaryHeader]
        ORDER BY [eshHeaderID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_EDI204SummaryHeader] OFF;
    END

DROP TABLE [dbo].[EDI204SummaryHeader];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_EDI204SummaryHeader]', N'EDI204SummaryHeader';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_EDI204SummaryHeader1]', N'PK_EDI204SummaryHeader', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

