DROP PROCEDURE [dbo].[CopyActRoleContactSecurity]
DROP PROCEDURE [dbo].[GetOrgActSecurityByRole];
DROP PROCEDURE [dbo].[InsOrgActRole];
DROP PROCEDURE [dbo].[CopyActRoleContactSecurityForSysAccount];
DROP PROCEDURE [dbo].[GetOrgActRole];
DROP PROCEDURE [dbo].[CopyActRoleOnJobCreate];
DROP PROCEDURE [dbo].[CopyActRoleOnProgramCreate];
DROP PROCEDURE [dbo].[CopyRefRoles];
DROP PROCEDURE [dbo].[GetActrolesByProgramId];
DROP PROCEDURE [dbo].[GetOrgActRoleView];
DROP PROCEDURE [dbo].[GetOrgActSecurityByRoleView];
DROP PROCEDURE [dbo].[GetOrgActSubSecurityByRole];
DROP PROCEDURE [dbo].[GetOrgActSubSecurityByRoleView];
DROP PROCEDURE [dbo].[InsOrgActSecurityByRole];
DROP PROCEDURE [dbo].[InsOrgActSubSecurityByRole];
DROP PROCEDURE [dbo].[InsOrUpdOrgActRole];
DROP PROCEDURE [dbo].[UpdOrgActRole];
DROP PROCEDURE [dbo].[UpdOrgActSecurityByRole];
DROP PROCEDURE [dbo].[UpdOrgActSubSecurityByRole];