select * from [SYSTM000ColumnsAlias] where ColTableName = 'job'


Update [SYSTM000ColumnsAlias] set IsGridColumn=0 --where ColTableName = 'job'
Update SYSTM000ColumnsAlias set IsGridColumn = 1 where ColTableName = 'job' and ColColumnName in (
'JobMITJobID'
,'JobSiteCode'
,'JobCustomerSalesOrder'
,'JobGatewayStatus'
,'StatusId'
,'JobDeliverySitePOC'
,'JobDeliverySitePOCPhone'
,'JobDeliverySitePOCEmail'
,'JobDeliverySiteName'
,'JobDeliveryStreetAddress'
,'JobDeliveryStreetAddress2'
,'JobDeliveryCity'
,'JobDeliveryState'
,'JobDeliveryPostalCode'
,'JobDeliveryDateTimePlanned'
,'JobDeliveryDateTimeActual'
,'JobOriginDateTimePlanned'
,'JobOriginDateTimeActual'
,'JobSellerSiteName'
,'JobDeliverySitePOCPhone2'
,'JobManifestNo'
,'PlantIDCode'
,'JobBOL'
,'JobQtyActual'
,'JobPartsActual'
,'JobTotalCubes'
,'JobServiceMode'
,'JobOrderedDate')