//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long AddressId { get; set; }
        public long SummaryHeaderId { get; set; }
        public byte AddressTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<long> NameID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string AltContName { get; set; }
        public string AltContNumber { get; set; }
        public string StreetAddress3 { get; set; }
        public string StreetAddress4 { get; set; }
        public string LocationID { get; set; }
        public string LocationName { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual SummaryHeader SummaryHeader { get; set; }
    }
}
