//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH040_Messages
    {
        public int Id { get; set; }
        public int LangId { get; set; }
        public string MessageCode { get; set; }
        public string MsgType { get; set; }
        public string MessageScreenTitle { get; set; }
        public string MessageTitle { get; set; }
        public string MessageDescription { get; set; }
        public string MessageInstruction { get; set; }
        public Nullable<int> MessageButtonSelection { get; set; }
    }
}
