//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH020_Token
    {
        public string Id { get; set; }
        public long UserId { get; set; }
        public string AuthClientId { get; set; }
        public System.DateTime IssuedUtc { get; set; }
        public System.DateTime ExpiresUtc { get; set; }
        public string AccessToken { get; set; }
        public bool IsLoggedIn { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
    
        public virtual SYSTM000OpnSezMe SYSTM000OpnSezMe { get; set; }
    }
}
