//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH050_UserPassword
    {
        public long UserId { get; set; }
        public string Password { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
    
        public virtual SYSTM000OpnSezMe SYSTM000OpnSezMe { get; set; }
    }
}
