//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWCDriverScrubReport
    {
        public Nullable<long> Id { get; set; }
        public int DriverScrubReportMasterId { get; set; }
    
        public virtual DriverScrubReportMaster DriverScrubReportMaster { get; set; }
    }
}
