//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonDriverScrubReport
    {
        public long Id { get; set; }
        public string QMSShippedOn { get; set; }
        public string QMSPSDisposition { get; set; }
        public string QMSStatusDescription { get; set; }
        public string FouthParty { get; set; }
        public string ThirdParty { get; set; }
        public string ActualControlId { get; set; }
        public string QMSControlId { get; set; }
        public string QRCGrouping { get; set; }
        public string QRCDescription { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public string ProductSubCategory2 { get; set; }
        public string ModelName { get; set; }
        public string CustomerBusinessType { get; set; }
        public string ChannelCD { get; set; }
        public string NationalAccountName { get; set; }
        public string CustomerName { get; set; }
        public string ShipFromLocation { get; set; }
        public string QMSRemark { get; set; }
        public Nullable<int> DaysToAccept { get; set; }
        public Nullable<int> QMSTotalUnit { get; set; }
        public Nullable<decimal> QMSTotalPrice { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual DriverScrubReportMaster DriverScrubReportMaster { get; set; }
    }
}
