//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsigneeSignatureInfo
    {
        public long ConsigneeSignatureInfoId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> JobId { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
