//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTC010Bridge
    {
        public long Id { get; set; }
        public long ConOrgId { get; set; }
        public Nullable<long> ContactMSTRID { get; set; }
        public string ConTableName { get; set; }
        public Nullable<long> ConPrimaryRecordId { get; set; }
        public Nullable<int> ConItemNumber { get; set; }
        public string ConTitle { get; set; }
        public Nullable<long> ConCodeId { get; set; }
        public Nullable<int> ConTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> ConIsDefault { get; set; }
        public byte[] ConDescription { get; set; }
        public byte[] ConInstruction { get; set; }
        public Nullable<int> ConTableTypeId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual ORGAN010Ref_Roles ORGAN010Ref_Roles { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
    }
}
