//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTC000Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTC000Master()
        {
            this.CONTC010Bridge = new HashSet<CONTC010Bridge>();
            this.CUST000Master = new HashSet<CUST000Master>();
            this.CUST000Master1 = new HashSet<CUST000Master>();
            this.CUST000Master2 = new HashSet<CUST000Master>();
            this.CUST040DCLocations = new HashSet<CUST040DCLocations>();
            this.JOBDL000Master = new HashSet<JOBDL000Master>();
            this.JOBDL000Master1 = new HashSet<JOBDL000Master>();
            this.JOBDL000Master2 = new HashSet<JOBDL000Master>();
            this.JOBDL000Master3 = new HashSet<JOBDL000Master>();
            this.JOBDL020Gateways = new HashSet<JOBDL020Gateways>();
            this.JOBDL020Gateways1 = new HashSet<JOBDL020Gateways>();
            this.ORGAN000Master1 = new HashSet<ORGAN000Master>();
            this.ORGAN000Master2 = new HashSet<ORGAN000Master>();
            this.ORGAN000Master3 = new HashSet<ORGAN000Master>();
            this.ORGAN010Ref_Roles = new HashSet<ORGAN010Ref_Roles>();
            this.PRGRM010Ref_GatewayDefaults = new HashSet<PRGRM010Ref_GatewayDefaults>();
            this.PRGRM010Ref_GatewayDefaults1 = new HashSet<PRGRM010Ref_GatewayDefaults>();
            this.PRGRM020Program_Role = new HashSet<PRGRM020Program_Role>();
            this.PRGRM051VendorLocations = new HashSet<PRGRM051VendorLocations>();
            this.SYSTM000OpnSezMe = new HashSet<SYSTM000OpnSezMe>();
            this.VEND000Master = new HashSet<VEND000Master>();
            this.VEND000Master1 = new HashSet<VEND000Master>();
            this.VEND000Master2 = new HashSet<VEND000Master>();
            this.VEND040DCLocations = new HashSet<VEND040DCLocations>();
        }
    
        public long Id { get; set; }
        public string ConERPId { get; set; }
        public string ConCompanyName { get; set; }
        public string ConLastName { get; set; }
        public string ConFirstName { get; set; }
        public string ConMiddleName { get; set; }
        public string ConEmailAddress { get; set; }
        public string ConEmailAddress2 { get; set; }
        public byte[] ConImage { get; set; }
        public string ConJobTitle { get; set; }
        public string ConBusinessPhone { get; set; }
        public string ConBusinessPhoneExt { get; set; }
        public string ConHomePhone { get; set; }
        public string ConMobilePhone { get; set; }
        public string ConFaxNumber { get; set; }
        public string ConBusinessAddress1 { get; set; }
        public string ConBusinessAddress2 { get; set; }
        public string ConBusinessCity { get; set; }
        public string ConBusinessZipPostal { get; set; }
        public string ConHomeAddress1 { get; set; }
        public string ConHomeAddress2 { get; set; }
        public string ConHomeCity { get; set; }
        public string ConHomeZipPostal { get; set; }
        public Nullable<int> ConAttachments { get; set; }
        public string ConWebPage { get; set; }
        public string ConNotes { get; set; }
        public string ConFullName { get; set; }
        public string ConFileAs { get; set; }
        public string ConOutlookId { get; set; }
        public string ConUDF02 { get; set; }
        public string ConUDF03 { get; set; }
        public string ConUDF04 { get; set; }
        public string ConUDF05 { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual COMP000Master COMP000Master { get; set; }
        public virtual SYSTM000Ref_States SYSTM000Ref_States { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_States SYSTM000Ref_States1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options4 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTC010Bridge> CONTC010Bridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST000Master> CUST000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST000Master> CUST000Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST000Master> CUST000Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST040DCLocations> CUST040DCLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL000Master> JOBDL000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL000Master> JOBDL000Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL000Master> JOBDL000Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL000Master> JOBDL000Master3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL020Gateways> JOBDL020Gateways { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL020Gateways> JOBDL020Gateways1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN000Master> ORGAN000Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN000Master> ORGAN000Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN000Master> ORGAN000Master3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN010Ref_Roles> ORGAN010Ref_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM010Ref_GatewayDefaults> PRGRM010Ref_GatewayDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM010Ref_GatewayDefaults> PRGRM010Ref_GatewayDefaults1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM020Program_Role> PRGRM020Program_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM051VendorLocations> PRGRM051VendorLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000OpnSezMe> SYSTM000OpnSezMe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND000Master> VEND000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND000Master> VEND000Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND000Master> VEND000Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND040DCLocations> VEND040DCLocations { get; set; }
    }
}
