//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST020BusinessTerms
    {
        public long Id { get; set; }
        public string LangCode { get; set; }
        public Nullable<long> CbtOrgID { get; set; }
        public Nullable<long> CbtCustomerId { get; set; }
        public Nullable<int> CbtItemNumber { get; set; }
        public string CbtCode { get; set; }
        public string CbtTitle { get; set; }
        public byte[] CbtDescription { get; set; }
        public Nullable<int> BusinessTermTypeId { get; set; }
        public Nullable<System.DateTime> CbtActiveDate { get; set; }
        public Nullable<decimal> CbtValue { get; set; }
        public Nullable<decimal> CbtHiThreshold { get; set; }
        public Nullable<decimal> CbtLoThreshold { get; set; }
        public Nullable<int> CbtAttachment { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual CUST000Master CUST000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
