//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST040DCLocations
    {
        public long Id { get; set; }
        public Nullable<long> CdcCustomerID { get; set; }
        public Nullable<int> CdcItemNumber { get; set; }
        public string CdcLocationCode { get; set; }
        public string CdcCustomerCode { get; set; }
        public string CdcLocationTitle { get; set; }
        public Nullable<long> CdcContactMSTRID { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual CUST000Master CUST000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
