//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST030DocumentReference
    {
        public long Id { get; set; }
        public Nullable<long> CdrOrgID { get; set; }
        public Nullable<long> CdrCustomerID { get; set; }
        public Nullable<int> CdrItemNumber { get; set; }
        public string CdrCode { get; set; }
        public string CdrTitle { get; set; }
        public Nullable<int> DocRefTypeId { get; set; }
        public Nullable<int> DocCategoryTypeId { get; set; }
        public byte[] CdrDescription { get; set; }
        public Nullable<int> CdrAttachment { get; set; }
        public Nullable<System.DateTime> CdrDateStart { get; set; }
        public Nullable<System.DateTime> CdrDateEnd { get; set; }
        public Nullable<bool> CdrRenewal { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual CUST000Master CUST000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
    }
}
