//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomAttribute
    {
        public long CustomAttributeId { get; set; }
        public long SummaryHeaderId { get; set; }
        public string CustomAttribute01 { get; set; }
        public string CustomAttribute02 { get; set; }
        public string CustomAttribute03 { get; set; }
        public string CustomAttribute04 { get; set; }
        public string CustomAttribute05 { get; set; }
        public string CustomAttribute06 { get; set; }
        public string CustomAttribute07 { get; set; }
        public string CustomAttribute08 { get; set; }
        public string CustomAttribute09 { get; set; }
        public string CustomAttribute10 { get; set; }
        public string CustomAttribute11 { get; set; }
        public string CustomAttribute12 { get; set; }
        public string CustomAttribute13 { get; set; }
        public string CustomAttribute14 { get; set; }
        public string CustomAttribute15 { get; set; }
        public string CustomAttribute16 { get; set; }
        public string CustomAttribute17 { get; set; }
        public string CustomAttribute18 { get; set; }
        public string CustomAttribute19 { get; set; }
        public string CustomAttribute20 { get; set; }
    
        public virtual SummaryHeader SummaryHeader { get; set; }
    }
}
