//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardCategoryRelation
    {
        public long DashboardCategoryRelationId { get; set; }
        public int DashboardSubCategory { get; set; }
        public string CustomQuery { get; set; }
        public string BackGroundColor { get; set; }
        public string FontColor { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual DashboardCategory DashboardCategory { get; set; }
    }
}
