//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AWCDriverScrubReport> AWCDriverScrubReport { get; set; }
        public virtual DbSet<CommonDriverScrubReport> CommonDriverScrubReport { get; set; }
        public virtual DbSet<COMP000Master> COMP000Master { get; set; }
        public virtual DbSet<COMPADD000Master> COMPADD000Master { get; set; }
        public virtual DbSet<CONTC000Master> CONTC000Master { get; set; }
        public virtual DbSet<CONTC010Bridge> CONTC010Bridge { get; set; }
        public virtual DbSet<CUST000Master> CUST000Master { get; set; }
        public virtual DbSet<CUST020BusinessTerms> CUST020BusinessTerms { get; set; }
        public virtual DbSet<CUST030DocumentReference> CUST030DocumentReference { get; set; }
        public virtual DbSet<CUST040DCLocations> CUST040DCLocations { get; set; }
        public virtual DbSet<CUST050Finacial_Cal> CUST050Finacial_Cal { get; set; }
        public virtual DbSet<Dashboard> Dashboard { get; set; }
        public virtual DbSet<DashboardCategory> DashboardCategory { get; set; }
        public virtual DbSet<DashboardCategoryRelation> DashboardCategoryRelation { get; set; }
        public virtual DbSet<DashboardSubCategory> DashboardSubCategory { get; set; }
        public virtual DbSet<DashboardType> DashboardType { get; set; }
        public virtual DbSet<DriverScrubReportMaster> DriverScrubReportMaster { get; set; }
        public virtual DbSet<EDI204SummaryDetail> EDI204SummaryDetail { get; set; }
        public virtual DbSet<EDI204SummaryHeader> EDI204SummaryHeader { get; set; }
        public virtual DbSet<EDI210Invoice> EDI210Invoice { get; set; }
        public virtual DbSet<EDI214ShipmentStatusDetail> EDI214ShipmentStatusDetail { get; set; }
        public virtual DbSet<EDI214ShipmentStatusHeader> EDI214ShipmentStatusHeader { get; set; }
        public virtual DbSet<EDI856ManifestDetail> EDI856ManifestDetail { get; set; }
        public virtual DbSet<EDI856ManifestHeader> EDI856ManifestHeader { get; set; }
        public virtual DbSet<EmailAttachment> EmailAttachment { get; set; }
        public virtual DbSet<EmailDetail> EmailDetail { get; set; }
        public virtual DbSet<EntitySequenceReference> EntitySequenceReference { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventEntityContentDetail> EventEntityContentDetail { get; set; }
        public virtual DbSet<EventEntityRelation> EventEntityRelation { get; set; }
        public virtual DbSet<EventSubscriber> EventSubscriber { get; set; }
        public virtual DbSet<EventSubscriberRelation> EventSubscriberRelation { get; set; }
        public virtual DbSet<EventSubscriberType> EventSubscriberType { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<JOBDL000Master> JOBDL000Master { get; set; }
        public virtual DbSet<JOBDL010Cargo> JOBDL010Cargo { get; set; }
        public virtual DbSet<JOBDL020Gateways> JOBDL020Gateways { get; set; }
        public virtual DbSet<JOBDL021GatewayExceptionCode> JOBDL021GatewayExceptionCode { get; set; }
        public virtual DbSet<JOBDL022GatewayExceptionReason> JOBDL022GatewayExceptionReason { get; set; }
        public virtual DbSet<JOBDL023GatewayInstallStatusMaster> JOBDL023GatewayInstallStatusMaster { get; set; }
        public virtual DbSet<JOBDL030Attributes> JOBDL030Attributes { get; set; }
        public virtual DbSet<JOBDL040DocumentReference> JOBDL040DocumentReference { get; set; }
        public virtual DbSet<JOBDL050Ref_Status> JOBDL050Ref_Status { get; set; }
        public virtual DbSet<JOBDL060Ref_CostSheetJob> JOBDL060Ref_CostSheetJob { get; set; }
        public virtual DbSet<JOBDL061BillableSheet> JOBDL061BillableSheet { get; set; }
        public virtual DbSet<JOBDL062CostSheet> JOBDL062CostSheet { get; set; }
        public virtual DbSet<JobDL070DeliveryUpdate> JobDL070DeliveryUpdate { get; set; }
        public virtual DbSet<JobDL070DeliveryUpdateProcessingLog> JobDL070DeliveryUpdateProcessingLog { get; set; }
        public virtual DbSet<JOBDL070ElectronicDataTransactions> JOBDL070ElectronicDataTransactions { get; set; }
        public virtual DbSet<JobDL085FarEyeDeliveryUpdate> JobDL085FarEyeDeliveryUpdate { get; set; }
        public virtual DbSet<JobUpdateDecisionMaker> JobUpdateDecisionMaker { get; set; }
        public virtual DbSet<Location000Master> Location000Master { get; set; }
        public virtual DbSet<MVOC000Program> MVOC000Program { get; set; }
        public virtual DbSet<MVOC010Ref_Questions> MVOC010Ref_Questions { get; set; }
        public virtual DbSet<NAV000JobOrderItemMapping> NAV000JobOrderItemMapping { get; set; }
        public virtual DbSet<NAV000JobOrderMapping> NAV000JobOrderMapping { get; set; }
        public virtual DbSet<NAV000JobPurchaseOrderMapping> NAV000JobPurchaseOrderMapping { get; set; }
        public virtual DbSet<NAV000JobSalesOrderMapping> NAV000JobSalesOrderMapping { get; set; }
        public virtual DbSet<OrderSearchConfig> OrderSearchConfig { get; set; }
        public virtual DbSet<ORGAN000Master> ORGAN000Master { get; set; }
        public virtual DbSet<ORGAN002MRKT_OrgSupport> ORGAN002MRKT_OrgSupport { get; set; }
        public virtual DbSet<ORGAN010Ref_Roles> ORGAN010Ref_Roles { get; set; }
        public virtual DbSet<ORGAN020Financial_Cal> ORGAN020Financial_Cal { get; set; }
        public virtual DbSet<ORGAN030Credentials> ORGAN030Credentials { get; set; }
        public virtual DbSet<ORGAN040_Roles> ORGAN040_Roles { get; set; }
        public virtual DbSet<PRGRM000Master> PRGRM000Master { get; set; }
        public virtual DbSet<PRGRM010Ref_GatewayDefaults> PRGRM010Ref_GatewayDefaults { get; set; }
        public virtual DbSet<PRGRM020_Roles> PRGRM020_Roles { get; set; }
        public virtual DbSet<PRGRM020Program_Role> PRGRM020Program_Role { get; set; }
        public virtual DbSet<PRGRM020Ref_AttributesDefault> PRGRM020Ref_AttributesDefault { get; set; }
        public virtual DbSet<PRGRM030ShipStatusReasonCodes> PRGRM030ShipStatusReasonCodes { get; set; }
        public virtual DbSet<PRGRM031ShipApptmtReasonCodes> PRGRM031ShipApptmtReasonCodes { get; set; }
        public virtual DbSet<PRGRM040ProgramBillableRate> PRGRM040ProgramBillableRate { get; set; }
        public virtual DbSet<PRGRM041ProgramCostRate> PRGRM041ProgramCostRate { get; set; }
        public virtual DbSet<PRGRM042ProgramBillableLocations> PRGRM042ProgramBillableLocations { get; set; }
        public virtual DbSet<PRGRM043ProgramCostLocations> PRGRM043ProgramCostLocations { get; set; }
        public virtual DbSet<PRGRM051VendorLocations> PRGRM051VendorLocations { get; set; }
        public virtual DbSet<PRGRM070EdiHeader> PRGRM070EdiHeader { get; set; }
        public virtual DbSet<PRGRM071EdiMapping> PRGRM071EdiMapping { get; set; }
        public virtual DbSet<PRGRM072EdiConditions> PRGRM072EdiConditions { get; set; }
        public virtual DbSet<SCN000Order> SCN000Order { get; set; }
        public virtual DbSet<SCN005Cargo> SCN005Cargo { get; set; }
        public virtual DbSet<SCN006CargoDetail> SCN006CargoDetail { get; set; }
        public virtual DbSet<SCN016DriverList> SCN016DriverList { get; set; }
        public virtual DbSet<SCN016RouteList> SCN016RouteList { get; set; }
        public virtual DbSet<SCR010CatalogList> SCR010CatalogList { get; set; }
        public virtual DbSet<SCR010InfoList> SCR010InfoList { get; set; }
        public virtual DbSet<SCR011OSDList> SCR011OSDList { get; set; }
        public virtual DbSet<SCR011OSDReasonList> SCR011OSDReasonList { get; set; }
        public virtual DbSet<SCR012RequirementList> SCR012RequirementList { get; set; }
        public virtual DbSet<SCR013ServiceList> SCR013ServiceList { get; set; }
        public virtual DbSet<SCR013ServicesList> SCR013ServicesList { get; set; }
        public virtual DbSet<SCR014ReturnReasonList> SCR014ReturnReasonList { get; set; }
        public virtual DbSet<SCR016GatewayList> SCR016GatewayList { get; set; }
        public virtual DbSet<SMTPServerDetail> SMTPServerDetail { get; set; }
        public virtual DbSet<SVYANS000Master> SVYANS000Master { get; set; }
        public virtual DbSet<SVYUSER000Master> SVYUSER000Master { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SYSMS010Ref_MessageTypes> SYSMS010Ref_MessageTypes { get; set; }
        public virtual DbSet<SYSTM000_StatusLog> SYSTM000_StatusLog { get; set; }
        public virtual DbSet<SYSTM000ColumnsAlias> SYSTM000ColumnsAlias { get; set; }
        public virtual DbSet<SYSTM000ColumnSettingsByUser> SYSTM000ColumnSettingsByUser { get; set; }
        public virtual DbSet<SYSTM000Delivery_Status> SYSTM000Delivery_Status { get; set; }
        public virtual DbSet<SYSTM000ErrorLog> SYSTM000ErrorLog { get; set; }
        public virtual DbSet<SYSTM000Master> SYSTM000Master { get; set; }
        public virtual DbSet<SYSTM000MenuDriver> SYSTM000MenuDriver { get; set; }
        public virtual DbSet<SYSTM000OpnSezMe> SYSTM000OpnSezMe { get; set; }
        public virtual DbSet<SYSTM000PhantomMaster> SYSTM000PhantomMaster { get; set; }
        public virtual DbSet<SYSTM000ProcessorMaster> SYSTM000ProcessorMaster { get; set; }
        public virtual DbSet<SYSTM000Ref_Dashboard> SYSTM000Ref_Dashboard { get; set; }
        public virtual DbSet<SYSTM000Ref_Lookup> SYSTM000Ref_Lookup { get; set; }
        public virtual DbSet<SYSTM000Ref_Options> SYSTM000Ref_Options { get; set; }
        public virtual DbSet<SYSTM000Ref_Report> SYSTM000Ref_Report { get; set; }
        public virtual DbSet<SYSTM000Ref_Settings> SYSTM000Ref_Settings { get; set; }
        public virtual DbSet<SYSTM000Ref_States> SYSTM000Ref_States { get; set; }
        public virtual DbSet<SYSTM000Ref_Table> SYSTM000Ref_Table { get; set; }
        public virtual DbSet<SYSTM000Ref_UserSettings> SYSTM000Ref_UserSettings { get; set; }
        public virtual DbSet<SYSTM000SecurityByRole> SYSTM000SecurityByRole { get; set; }
        public virtual DbSet<SYSTM000Validation> SYSTM000Validation { get; set; }
        public virtual DbSet<SYSTM000VdcLocationPreferences> SYSTM000VdcLocationPreferences { get; set; }
        public virtual DbSet<SYSTM000VideoCategory> SYSTM000VideoCategory { get; set; }
        public virtual DbSet<SYSTM000VideoDetail> SYSTM000VideoDetail { get; set; }
        public virtual DbSet<SYSTM000ZipcodeMaster> SYSTM000ZipcodeMaster { get; set; }
        public virtual DbSet<SYSTM010MenuAccessLevel> SYSTM010MenuAccessLevel { get; set; }
        public virtual DbSet<SYSTM010MenuOptionLevel> SYSTM010MenuOptionLevel { get; set; }
        public virtual DbSet<SYSTM010Ref_Options> SYSTM010Ref_Options { get; set; }
        public virtual DbSet<SYSTM010SubSecurityByRole> SYSTM010SubSecurityByRole { get; set; }
        public virtual DbSet<SYSTM020Ref_Attachments> SYSTM020Ref_Attachments { get; set; }
        public virtual DbSet<SYSTM030Ref_TabPageName> SYSTM030Ref_TabPageName { get; set; }
        public virtual DbSet<SYSTM040ProcessorConfig> SYSTM040ProcessorConfig { get; set; }
        public virtual DbSet<SYSTM041ProcessorErrorLog> SYSTM041ProcessorErrorLog { get; set; }
        public virtual DbSet<VEND000Master> VEND000Master { get; set; }
        public virtual DbSet<VEND020BusinessTerms> VEND020BusinessTerms { get; set; }
        public virtual DbSet<VEND030DocumentReference> VEND030DocumentReference { get; set; }
        public virtual DbSet<VEND040DCLocations> VEND040DCLocations { get; set; }
        public virtual DbSet<VEND050Finacial_Cal> VEND050Finacial_Cal { get; set; }
        public virtual DbSet<XcblSummaryDetail> XcblSummaryDetail { get; set; }
        public virtual DbSet<XcblSummaryHeader> XcblSummaryHeader { get; set; }
        public virtual DbSet<ConsigneeSignatureInfo> ConsigneeSignatureInfo { get; set; }
        public virtual DbSet<NAV000Customer> NAV000Customer { get; set; }
        public virtual DbSet<NAV000OrderMapping> NAV000OrderMapping { get; set; }
        public virtual DbSet<NAV000Vendor> NAV000Vendor { get; set; }
        public virtual DbSet<SCN001OrderSignature> SCN001OrderSignature { get; set; }
        public virtual DbSet<SCN007CargoBCPhoto> SCN007CargoBCPhoto { get; set; }
        public virtual DbSet<SCN013OrderServicesPhoto> SCN013OrderServicesPhoto { get; set; }
        public virtual DbSet<SCN014OrderOSD> SCN014OrderOSD { get; set; }
        public virtual DbSet<SCN014OSDPhoto> SCN014OSDPhoto { get; set; }
        public virtual DbSet<SCN015OrderRequirementPhoto> SCN015OrderRequirementPhoto { get; set; }
        public virtual DbSet<SCN017UserAuth> SCN017UserAuth { get; set; }
        public virtual DbSet<Sys000AuditTrail> Sys000AuditTrail { get; set; }
        public virtual DbSet<systranschemas> systranschemas { get; set; }
        public virtual DbSet<TestJobGateway> TestJobGateway { get; set; }
        public virtual DbSet<XCBL_MER000Authentication> XCBL_MER000Authentication { get; set; }
        public virtual DbSet<XCBL_MER010TransactionLog> XCBL_MER010TransactionLog { get; set; }
        public virtual DbSet<vwGetVocReportData> vwGetVocReportData { get; set; }
    }
}
