//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverScrubReportMaster
    {
        public int Id { get; set; }
        public long CustomerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual CUST000Master CUST000Master { get; set; }
        public virtual AWCDriverScrubReport AWCDriverScrubReport { get; set; }
    }
}
