//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI214ShipmentStatusHeader
    {
        public long eshHeaderID { get; set; }
        public string eshTradingPartner { get; set; }
        public string eshOrderNumber { get; set; }
        public string eshShipmentID { get; set; }
        public string eshSCAC { get; set; }
        public string eshDomicileSiteNo { get; set; }
        public string eshRouteNumber { get; set; }
        public string eshSignedBy { get; set; }
        public string eshTerminalName { get; set; }
        public string eshTerminalAddress1 { get; set; }
        public string eshTerminalAddress2 { get; set; }
        public string eshTerminalCity { get; set; }
        public string eshTerminalState { get; set; }
        public string eshTerminalPostalCode { get; set; }
        public string eshTerminalCountryCode { get; set; }
        public string eshStatus { get; set; }
        public string eshStatusReason { get; set; }
        public string eshStatusDate { get; set; }
        public string eshStatusTime { get; set; }
        public string eshLocationCity { get; set; }
        public string eshLocationState { get; set; }
        public string eshLocationCountryCode { get; set; }
        public string eshLatitude { get; set; }
        public string eshLongitude { get; set; }
        public string eshDirection { get; set; }
        public Nullable<long> eshOverage { get; set; }
        public Nullable<long> eshPartial { get; set; }
        public Nullable<long> eshDamage { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public string eshEquipmentNumber { get; set; }
        public string eshOrderType { get; set; }
        public string eshWeightQualifier { get; set; }
        public string eshWeightUnitCode { get; set; }
        public Nullable<decimal> eshWeight { get; set; }
        public Nullable<long> eshQuanity { get; set; }
        public Nullable<long> eshParts { get; set; }
        public string eshVolumeQualifier { get; set; }
        public Nullable<decimal> eshVolume { get; set; }
    }
}
