//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI204SummaryDetail
    {
        public long esdDetailID { get; set; }
        public Nullable<long> eshHeaderID { get; set; }
        public string esdTradingPartner { get; set; }
        public string esdBOLNo { get; set; }
        public string esdManifestNo { get; set; }
        public string esdCommodityType { get; set; }
        public string esdCommodityDescription { get; set; }
        public string esdUnitOfMeasure { get; set; }
        public Nullable<decimal> esdWeight { get; set; }
        public Nullable<long> esdQuantity { get; set; }
        public Nullable<decimal> esdCubicFeet { get; set; }
        public string esdUDF01 { get; set; }
        public string esdUDF02 { get; set; }
        public string esdUDF03 { get; set; }
        public string esdUDF04 { get; set; }
        public string esdUDF05 { get; set; }
        public string esdUDF06 { get; set; }
        public string esdUDF07 { get; set; }
        public string esdUDF08 { get; set; }
        public string esdUDF09 { get; set; }
        public string esdUDF10 { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    }
}
