//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI204SummaryHeader
    {
        public long eshHeaderID { get; set; }
        public string eshTradingPartner { get; set; }
        public Nullable<long> eshGroupControlNo { get; set; }
        public string eshBOLNo { get; set; }
        public string eshMasterBOLNo { get; set; }
        public string eshMethodOfPayment { get; set; }
        public string eshSetPurpose { get; set; }
        public string eshCustomerReferenceNo { get; set; }
        public string eshLocationId { get; set; }
        public string eshShipDescription { get; set; }
        public string eshOrderType { get; set; }
        public string eshPurchaseOrderNo { get; set; }
        public string eshLocationNumber { get; set; }
        public Nullable<System.DateTime> eshShipDate { get; set; }
        public Nullable<System.DateTime> eshArrivalDate3PL { get; set; }
        public string eshServiceMode { get; set; }
        public string eshProductType { get; set; }
        public string eshLatitude { get; set; }
        public string eshLongitude { get; set; }
        public string eshReasonCodeCancellation { get; set; }
        public string eshManifestNo { get; set; }
        public Nullable<decimal> eshTotalWeight { get; set; }
        public Nullable<decimal> eshTotalCubicFeet { get; set; }
        public Nullable<long> eshTotalPieces { get; set; }
        public string eshDeliveryCommitmentType { get; set; }
        public Nullable<System.DateTime> eshScheduledPickupDate { get; set; }
        public Nullable<System.DateTime> eshScheduledDeliveryDate { get; set; }
        public string eshSpecialNotes { get; set; }
        public string eshConsigneeName { get; set; }
        public Nullable<long> eshConsigneeNameID { get; set; }
        public string eshConsigneeAddress1 { get; set; }
        public string eshConsigneeAddress2 { get; set; }
        public string eshConsigneeCity { get; set; }
        public string eshConsigneeState { get; set; }
        public string eshConsigneePostalCode { get; set; }
        public string eshConsigneeCountryCode { get; set; }
        public string eshConsigneeContactName { get; set; }
        public string eshConsigneeContactNumber { get; set; }
        public string eshConsigneeAltContName { get; set; }
        public string eshConsigneeAltContNumber { get; set; }
        public string eshInterConsigneeName { get; set; }
        public Nullable<long> eshInterConsigneeNameID { get; set; }
        public string eshInterConsigneeAddress1 { get; set; }
        public string eshInterConsigneeAddress2 { get; set; }
        public string eshInterConsigneeCity { get; set; }
        public string eshInterConsigneeState { get; set; }
        public string eshInterConsigneePostalCode { get; set; }
        public string eshInterConsigneeCountryCode { get; set; }
        public string eshInterConsigneeContactName { get; set; }
        public string eshInterConsigneeContactNumber { get; set; }
        public string eshInterConsigneeAltContName { get; set; }
        public string eshInterConsigneeAltContNumber { get; set; }
        public string eshShipFromName { get; set; }
        public Nullable<long> eshShipFromNameID { get; set; }
        public string eshShipFromAddress1 { get; set; }
        public string eshShipFromAddress2 { get; set; }
        public string eshShipFromCity { get; set; }
        public string eshShipFromState { get; set; }
        public string eshShipFromPostalCode { get; set; }
        public string eshShipFromCountryCode { get; set; }
        public string eshShipFromContactName { get; set; }
        public string eshShipFromContactNumber { get; set; }
        public string eshShipFromAltContName { get; set; }
        public string eshShipFromAltContNumber { get; set; }
        public string eshBillToName { get; set; }
        public Nullable<long> eshBillToNameID { get; set; }
        public string eshBillToAddress1 { get; set; }
        public string eshBillToAddress2 { get; set; }
        public string eshBillToCity { get; set; }
        public string eshBillToState { get; set; }
        public string eshBillToPostalCode { get; set; }
        public string eshBillToCountryCode { get; set; }
        public string eshBillToContactName { get; set; }
        public string eshBillToContactNumber { get; set; }
        public string eshBillToAltContName { get; set; }
        public string eshBillToAltContNumber { get; set; }
        public string eshTextData { get; set; }
        public string eshUDF01 { get; set; }
        public string eshUDF02 { get; set; }
        public string eshUDF03 { get; set; }
        public string eshUDF04 { get; set; }
        public string eshUDF05 { get; set; }
        public string eshUDF06 { get; set; }
        public string eshUDF07 { get; set; }
        public string eshUDF08 { get; set; }
        public string eshUDF09 { get; set; }
        public string eshUDF10 { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    }
}
