//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI856ManifestDetail
    {
        public long emdDetailID { get; set; }
        public Nullable<long> emhHeaderID { get; set; }
        public string emdTradingPartner { get; set; }
        public Nullable<int> emdGroupControlNo { get; set; }
        public string emdBOLNo { get; set; }
        public string emdManifestNo { get; set; }
        public Nullable<decimal> emdItemWeight { get; set; }
        public string emdWeightQualifier { get; set; }
        public string emdWeightUnitOfMeasure { get; set; }
        public Nullable<decimal> emdItemVolume { get; set; }
        public string emdVolumeQualifier { get; set; }
        public string emdVolumeUnitOfMeasure { get; set; }
        public Nullable<int> emdItemQuantity { get; set; }
        public string emdBarCodeSerialNumber { get; set; }
        public string emdItemDescription { get; set; }
        public string emdShipQuantity { get; set; }
        public string emdPackagingCode { get; set; }
        public string emdCommodityCode { get; set; }
        public string emdMasterLblQualifier { get; set; }
        public string emdMasterSerialNumber { get; set; }
        public string emdUDF01 { get; set; }
        public string emdUDF02 { get; set; }
        public string emdUDF03 { get; set; }
        public string emdUDF04 { get; set; }
        public string emdUDF05 { get; set; }
        public string emdUDF06 { get; set; }
        public string emdUDF07 { get; set; }
        public string emdUDF08 { get; set; }
        public string emdUDF09 { get; set; }
        public string emdUDF10 { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    }
}
