//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI856ManifestHeader
    {
        public long emhHeaderID { get; set; }
        public string emhTradingPartner { get; set; }
        public Nullable<long> emhGroupControlNo { get; set; }
        public string emhMasterBOLNo { get; set; }
        public string emhOrderTotal { get; set; }
        public string emhCustomerReferenceNo { get; set; }
        public string emhLMSLocationID { get; set; }
        public string emhShipmentDestCode { get; set; }
        public string emhOrderType { get; set; }
        public string emhPurchaseOrderNo { get; set; }
        public string emhBOLNo { get; set; }
        public string emhLocationNumber { get; set; }
        public string emhOriginalShipFromLocation { get; set; }
        public string emhLatitude { get; set; }
        public string emhLongitude { get; set; }
        public string emhShipDescription { get; set; }
        public Nullable<System.DateTime> emhPromisedDeliveryDate { get; set; }
        public Nullable<System.DateTime> emhScheduledDeliveryDate { get; set; }
        public string emhOrderATGroup { get; set; }
        public string emhManifestNo { get; set; }
        public Nullable<System.DateTime> emhDateSent { get; set; }
        public Nullable<System.DateTime> emhTimeSent { get; set; }
        public Nullable<System.DateTime> emhShippedDate { get; set; }
        public Nullable<System.DateTime> emhEstimatedDeliveryDate { get; set; }
        public string emhPackType { get; set; }
        public Nullable<long> emhTotalQuantity { get; set; }
        public string emhCommodityCode { get; set; }
        public string emhLadingDescription { get; set; }
        public Nullable<decimal> emhTotalWeight { get; set; }
        public Nullable<decimal> emhItemWeight { get; set; }
        public string emhWeightQualifier { get; set; }
        public Nullable<decimal> emhTotalVolume { get; set; }
        public string emhVolumeQualifier { get; set; }
        public string emhVolumeUnitOfMeasure { get; set; }
        public string emhOriginCarrier { get; set; }
        public string emhCarrierSCAC { get; set; }
        public string emhTransportationMethod { get; set; }
        public string emhEquipmentInitials { get; set; }
        public string emhEquipmentNumber { get; set; }
        public string emhConsigneeName { get; set; }
        public string emhConsigneeAddress1 { get; set; }
        public string emhConsigneeAddress2 { get; set; }
        public string emhConsigneeCity { get; set; }
        public string emhConsigneeState { get; set; }
        public string emhConsigneePostalCode { get; set; }
        public string emhConsigneeCountryCode { get; set; }
        public string emhConsigneeContactName { get; set; }
        public string emhConsigneeContactNumber { get; set; }
        public string emhConsigneeAltContName { get; set; }
        public string emhConsigneeAltContNumber { get; set; }
        public string emhInterConsigneeName { get; set; }
        public string emhInterConsigneeAddress1 { get; set; }
        public string emhInterConsigneeAddress2 { get; set; }
        public string emhInterConsigneeCity { get; set; }
        public string emhInterConsigneeState { get; set; }
        public string emhInterConsigneePostalCode { get; set; }
        public string emhInterConsigneeCountryCode { get; set; }
        public string emhInterConsigneeContactName { get; set; }
        public string emhInterConsigneeContactNumber { get; set; }
        public string emhInterConsigneeAltContName { get; set; }
        public string emhInterConsigneeAltContNumber { get; set; }
        public string emhShipFromName { get; set; }
        public string emhShipFromAddress1 { get; set; }
        public string emhShipFromAddress2 { get; set; }
        public string emhShipFromCity { get; set; }
        public string emhShipFromState { get; set; }
        public string emhShipFromPostalCode { get; set; }
        public string emhShipFromCountryCode { get; set; }
        public string emhShipFromContactName { get; set; }
        public string emhShipFromContactNumber { get; set; }
        public string emhShipFromAltContName { get; set; }
        public string emhShipFromAltContNumber { get; set; }
        public string emhBillToName { get; set; }
        public string emhBillToAddress1 { get; set; }
        public string emhBillToAddress2 { get; set; }
        public string emhBillToCity { get; set; }
        public string emhBillToState { get; set; }
        public string emhBillToPostalCode { get; set; }
        public string emhBillToCountryCode { get; set; }
        public string emhBillToContactName { get; set; }
        public string emhBillToContactNumber { get; set; }
        public string emhBillToAltContName { get; set; }
        public string emhBillToAltContNumber { get; set; }
        public string emhTextData { get; set; }
        public string emhUDF01 { get; set; }
        public string emhUDF02 { get; set; }
        public string emhUDF03 { get; set; }
        public string emhUDF04 { get; set; }
        public string emhUDF05 { get; set; }
        public string emhUDF06 { get; set; }
        public string emhUDF07 { get; set; }
        public string emhUDF08 { get; set; }
        public string emhUDF09 { get; set; }
        public string emhUDF10 { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
        public string emhConsigneeStreetAddress3 { get; set; }
        public string emhConsigneeStreetAddress4 { get; set; }
        public string emhInterConsigneeStreetAddress3 { get; set; }
        public string emhInterConsigneeStreetAddress4 { get; set; }
        public string emhBillToStreetAddress3 { get; set; }
        public string emhBillToStreetAddress4 { get; set; }
        public string emhShipFromStreetAddress3 { get; set; }
        public string emhShipFromStreetAddress4 { get; set; }
        public string emhConsigneeContactEmail { get; set; }
        public string emhConsigneeAltContEmail { get; set; }
        public string emhInterConsigneeContactEmail { get; set; }
        public string emhInterConsigneeAltContEmail { get; set; }
        public string emhShipFromContactEmail { get; set; }
        public string emhShipFromAltContEmail { get; set; }
        public string emhBillToContactEmail { get; set; }
        public string emhBillToAltContEmail { get; set; }
    }
}
