//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySequenceReference
    {
        public int Id { get; set; }
        public long SequenceNumber { get; set; }
        public string Entity { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
