//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ErrorLogId { get; set; }
        public string SourceApplication { get; set; }
        public string SourceClass { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<byte> Severity { get; set; }
        public string AdditionalMessage { get; set; }
        public string ExceptionMessage { get; set; }
        public string StackTrace { get; set; }
        public string AssignTo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string AssigneeComments { get; set; }
        public Nullable<byte> TraceLevel { get; set; }
        public string MachineName { get; set; }
    }
}
