//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSubscriberRelation
    {
        public int Id { get; set; }
        public int SubscriberId { get; set; }
        public int EventEntityRelationId { get; set; }
        public string EmailAddresses { get; set; }
        public int EventSubscriberTypeId { get; set; }
    
        public virtual EventEntityRelation EventEntityRelation { get; set; }
        public virtual EventSubscriber EventSubscriber { get; set; }
        public virtual EventSubscriberType EventSubscriberType { get; set; }
    }
}
