//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBDL061BillableSheet
    {
        public long Id { get; set; }
        public Nullable<long> JobID { get; set; }
        public string PrcLineItem { get; set; }
        public Nullable<int> PrcChargeID { get; set; }
        public string PrcChargeCode { get; set; }
        public string PrcTitle { get; set; }
        public Nullable<long> PrcSurchargeOrder { get; set; }
        public Nullable<double> PrcSurchargePercent { get; set; }
        public Nullable<int> ChargeTypeId { get; set; }
        public Nullable<int> PrcNumberUsed { get; set; }
        public Nullable<decimal> PrcDuration { get; set; }
        public Nullable<decimal> PrcQuantity { get; set; }
        public Nullable<int> PrcUnitId { get; set; }
        public Nullable<decimal> PrcRate { get; set; }
        public Nullable<decimal> PrcAmount { get; set; }
        public Nullable<double> PrcMarkupPercent { get; set; }
        public byte[] PrcComments { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual JOBDL000Master JOBDL000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
