//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDL085FarEyeDeliveryUpdate
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public string DeliveryUpdateRequest { get; set; }
        public string DeliveryUpdateResponse { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
    }
}
