//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBDL000Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOBDL000Master()
        {
            this.JOBDL061BillableSheet = new HashSet<JOBDL061BillableSheet>();
            this.JOBDL062CostSheet = new HashSet<JOBDL062CostSheet>();
            this.JOBDL010Cargo = new HashSet<JOBDL010Cargo>();
            this.JOBDL020Gateways = new HashSet<JOBDL020Gateways>();
            this.JOBDL030Attributes = new HashSet<JOBDL030Attributes>();
            this.JOBDL040DocumentReference = new HashSet<JOBDL040DocumentReference>();
            this.JOBDL050Ref_Status = new HashSet<JOBDL050Ref_Status>();
            this.JOBDL060Ref_CostSheetJob = new HashSet<JOBDL060Ref_CostSheetJob>();
            this.NAV000JobOrderMapping = new HashSet<NAV000JobOrderMapping>();
            this.SYSTM000_StatusLog = new HashSet<SYSTM000_StatusLog>();
        }
    
        public long Id { get; set; }
        public Nullable<long> JobMITJobID { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public string JobSiteCode { get; set; }
        public string JobConsigneeCode { get; set; }
        public string JobCustomerSalesOrder { get; set; }
        public string JobBOL { get; set; }
        public string JobBOLMaster { get; set; }
        public string JobBOLChild { get; set; }
        public string JobCustomerPurchaseOrder { get; set; }
        public string JobCarrierContract { get; set; }
        public string JobManifestNo { get; set; }
        public Nullable<decimal> JobQtyOrdered { get; set; }
        public Nullable<decimal> JobQtyActual { get; set; }
        public Nullable<int> JobQtyUnitTypeId { get; set; }
        public Nullable<decimal> JobPartsOrdered { get; set; }
        public Nullable<decimal> JobPartsActual { get; set; }
        public Nullable<decimal> JobTotalCubes { get; set; }
        public string JobServiceMode { get; set; }
        public string JobChannel { get; set; }
        public string JobProductType { get; set; }
        public string JobGatewayStatus { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> JobStatusedDate { get; set; }
        public Nullable<bool> JobCompleted { get; set; }
        public string JobType { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<long> JobDeliveryAnalystContactID { get; set; }
        public Nullable<long> JobDeliveryResponsibleContactID { get; set; }
        public string PlantIDCode { get; set; }
        public Nullable<int> JobRouteId { get; set; }
        public Nullable<long> JobDriverId { get; set; }
        public string JobStop { get; set; }
        public string CarrierID { get; set; }
        public string JobSignText { get; set; }
        public string JobSignLatitude { get; set; }
        public string JobSignLongitude { get; set; }
        public Nullable<System.DateTime> WindowDelStartTime { get; set; }
        public Nullable<System.DateTime> WindowDelEndTime { get; set; }
        public Nullable<System.DateTime> WindowPckStartTime { get; set; }
        public Nullable<System.DateTime> WindowPckEndTime { get; set; }
        public string JobDeliverySitePOC { get; set; }
        public string JobDeliverySitePOCPhone { get; set; }
        public string JobDeliverySitePOCEmail { get; set; }
        public string JobDeliverySiteName { get; set; }
        public string JobDeliveryStreetAddress { get; set; }
        public string JobDeliveryStreetAddress2 { get; set; }
        public string JobDeliveryCity { get; set; }
        public string JobDeliveryState { get; set; }
        public string JobDeliveryPostalCode { get; set; }
        public string JobDeliveryCountry { get; set; }
        public string JobDeliveryTimeZone { get; set; }
        public Nullable<System.DateTime> JobDeliveryDateTimePlanned { get; set; }
        public Nullable<System.DateTime> JobDeliveryDateTimeActual { get; set; }
        public Nullable<System.DateTime> JobDeliveryDateTimeBaseline { get; set; }
        public byte[] JobDeliveryComment { get; set; }
        public string JobDeliveryRecipientPhone { get; set; }
        public string JobDeliveryRecipientEmail { get; set; }
        public string JobLatitude { get; set; }
        public string JobLongitude { get; set; }
        public Nullable<long> JobOriginResponsibleContactID { get; set; }
        public string JobOriginSiteCode { get; set; }
        public string JobOriginSitePOC { get; set; }
        public string JobOriginSitePOCPhone { get; set; }
        public string JobOriginSitePOCEmail { get; set; }
        public string JobOriginSiteName { get; set; }
        public string JobOriginStreetAddress { get; set; }
        public string JobOriginStreetAddress2 { get; set; }
        public string JobOriginCity { get; set; }
        public string JobOriginState { get; set; }
        public string JobOriginPostalCode { get; set; }
        public string JobOriginCountry { get; set; }
        public string JobOriginTimeZone { get; set; }
        public Nullable<System.DateTime> JobOriginDateTimePlanned { get; set; }
        public Nullable<System.DateTime> JobOriginDateTimeActual { get; set; }
        public Nullable<System.DateTime> JobOriginDateTimeBaseline { get; set; }
        public string JobProcessingFlags { get; set; }
        public string JobDeliverySitePOC2 { get; set; }
        public string JobDeliverySitePOCPhone2 { get; set; }
        public string JobDeliverySitePOCEmail2 { get; set; }
        public string JobOriginSitePOC2 { get; set; }
        public string JobOriginSitePOCPhone2 { get; set; }
        public string JobOriginSitePOCEmail2 { get; set; }
        public string JobSellerCode { get; set; }
        public string JobSellerSitePOC { get; set; }
        public string JobSellerSitePOCPhone { get; set; }
        public string JobSellerSitePOCEmail { get; set; }
        public string JobSellerSitePOC2 { get; set; }
        public string JobSellerSitePOCPhone2 { get; set; }
        public string JobSellerSitePOCEmail2 { get; set; }
        public string JobSellerSiteName { get; set; }
        public string JobSellerStreetAddress { get; set; }
        public string JobSellerStreetAddress2 { get; set; }
        public string JobSellerCity { get; set; }
        public string JobSellerState { get; set; }
        public string JobSellerPostalCode { get; set; }
        public string JobSellerCountry { get; set; }
        public string JobUser01 { get; set; }
        public string JobUser02 { get; set; }
        public string JobUser03 { get; set; }
        public string JobUser04 { get; set; }
        public string JobUser05 { get; set; }
        public string JobStatusFlags { get; set; }
        public string JobScannerFlags { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> JobOrderedDate { get; set; }
        public Nullable<System.DateTime> JobShipmentDate { get; set; }
        public Nullable<System.DateTime> JobInvoicedDate { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual CONTC000Master CONTC000Master1 { get; set; }
        public virtual CONTC000Master CONTC000Master2 { get; set; }
        public virtual CONTC000Master CONTC000Master3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL061BillableSheet> JOBDL061BillableSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL062CostSheet> JOBDL062CostSheet { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL010Cargo> JOBDL010Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL020Gateways> JOBDL020Gateways { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL030Attributes> JOBDL030Attributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL040DocumentReference> JOBDL040DocumentReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL050Ref_Status> JOBDL050Ref_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL060Ref_CostSheetJob> JOBDL060Ref_CostSheetJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAV000JobOrderMapping> NAV000JobOrderMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000_StatusLog> SYSTM000_StatusLog { get; set; }
    }
}
