//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBDL020Gateways
    {
        public long Id { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<int> GwyGatewaySortOrder { get; set; }
        public string GwyGatewayCode { get; set; }
        public string GwyGatewayTitle { get; set; }
        public byte[] GwyGatewayDescription { get; set; }
        public Nullable<decimal> GwyGatewayDuration { get; set; }
        public Nullable<bool> GwyGatewayDefault { get; set; }
        public Nullable<int> GatewayTypeId { get; set; }
        public Nullable<long> GwyGatewayAnalyst { get; set; }
        public Nullable<long> GwyGatewayResponsible { get; set; }
        public string GwyPerson { get; set; }
        public string GwyPhone { get; set; }
        public string GwyEmail { get; set; }
        public string GwyTitle { get; set; }
        public Nullable<System.DateTime> GwyDDPCurrent { get; set; }
        public Nullable<System.DateTime> GwyDDPNew { get; set; }
        public Nullable<decimal> GwyUprWindow { get; set; }
        public Nullable<decimal> GwyLwrWindow { get; set; }
        public Nullable<System.DateTime> GwyUprDate { get; set; }
        public Nullable<System.DateTime> GwyLwrDate { get; set; }
        public Nullable<System.DateTime> GwyGatewayPCD { get; set; }
        public Nullable<System.DateTime> GwyGatewayECD { get; set; }
        public Nullable<System.DateTime> GwyGatewayACD { get; set; }
        public Nullable<bool> GwyCompleted { get; set; }
        public Nullable<int> GatewayUnitId { get; set; }
        public Nullable<int> GwyAttachments { get; set; }
        public byte[] GwyComment { get; set; }
        public string GwyProcessingFlags { get; set; }
        public Nullable<int> GwyDateRefTypeId { get; set; }
        public Nullable<bool> Scanner { get; set; }
        public string GwyShipStatusReasonCode { get; set; }
        public string GwyShipApptmtReasonCode { get; set; }
        public string GwyOrderType { get; set; }
        public string GwyShipmentType { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> GwyUpdatedById { get; set; }
        public Nullable<System.DateTime> GwyClosedOn { get; set; }
        public string GwyClosedBy { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual CONTC000Master CONTC000Master1 { get; set; }
        public virtual JOBDL000Master JOBDL000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options4 { get; set; }
    }
}
