//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBDL062CostSheet
    {
        public long Id { get; set; }
        public Nullable<long> JobID { get; set; }
        public string CstLineItem { get; set; }
        public Nullable<int> CstChargeID { get; set; }
        public string CstChargeCode { get; set; }
        public string CstTitle { get; set; }
        public Nullable<long> CstSurchargeOrder { get; set; }
        public Nullable<double> CstSurchargePercent { get; set; }
        public Nullable<int> ChargeTypeId { get; set; }
        public Nullable<int> CstNumberUsed { get; set; }
        public Nullable<decimal> CstDuration { get; set; }
        public Nullable<decimal> CstQuantity { get; set; }
        public Nullable<int> CstUnitId { get; set; }
        public Nullable<decimal> CstRate { get; set; }
        public Nullable<decimal> CstAmount { get; set; }
        public Nullable<double> CstMarkupPercent { get; set; }
        public byte[] CstComments { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual JOBDL000Master JOBDL000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
