//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBDL040DocumentReference
    {
        public long Id { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<int> JdrItemNumber { get; set; }
        public string JdrCode { get; set; }
        public string JdrTitle { get; set; }
        public Nullable<int> DocTypeId { get; set; }
        public byte[] JdrDescription { get; set; }
        public Nullable<int> JdrAttachment { get; set; }
        public Nullable<System.DateTime> JdrDateStart { get; set; }
        public Nullable<System.DateTime> JdrDateEnd { get; set; }
        public Nullable<bool> JdrRenewal { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual JOBDL000Master JOBDL000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
