//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobUpdateDecisionMaker
    {
        public int JobUpdateDecisionMakerId { get; set; }
        public string ActionCode { get; set; }
        public string xCBLColumnName { get; set; }
        public string JobColumnName { get; set; }
        public bool IsAutoUpdate { get; set; }
        public string XcblTableName { get; set; }
    }
}
