//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineDetail
    {
        public long LineDetailId { get; set; }
        public long SummaryHeaderId { get; set; }
        public string LineNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> ShipQuantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUnitOfMeasure { get; set; }
        public string Volume { get; set; }
        public string VolumeUnitOfMeasure { get; set; }
        public string SecondaryLocation { get; set; }
        public string MaterialType { get; set; }
        public string ShipUnitOfMeasure { get; set; }
        public string CustomerStockNumber { get; set; }
        public string StatusCode { get; set; }
        public string EDILINEID { get; set; }
        public string MaterialTypeDescription { get; set; }
        public string LineNumberReference { get; set; }
    
        public virtual SummaryHeader SummaryHeader { get; set; }
    }
}
