//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location000Master
    {
        public long Id { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string TimeZoneShortName { get; set; }
        public Nullable<int> UTC { get; set; }
        public Nullable<bool> IsDaylightSaving { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Country { get; set; }
        public string TimeZone { get; set; }
        public string TimeZoneAbbreviation { get; set; }
    }
}
