//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVOC000Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVOC000Program()
        {
            this.MVOC010Ref_Questions = new HashSet<MVOC010Ref_Questions>();
        }
    
        public long Id { get; set; }
        public Nullable<long> VocOrgID { get; set; }
        public Nullable<long> VocProgramID { get; set; }
        public string VocSurveyCode { get; set; }
        public string VocSurveyTitle { get; set; }
        public byte[] VocDescription { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> VocDateOpen { get; set; }
        public Nullable<System.DateTime> VocDateClose { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
        public bool VocAllStar { get; set; }
    
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVOC010Ref_Questions> MVOC010Ref_Questions { get; set; }
    }
}
