//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVOC020Answers
    {
        public long Id { get; set; }
        public long AnsJobId { get; set; }
        public System.DateTime AnsDateTime { get; set; }
        public long AnsQuestionNumber { get; set; }
        public string AnsQuestionCode { get; set; }
        public string AnsQuestionText { get; set; }
        public string AnsResponse { get; set; }
    }
}
