//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVOC010Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVOC010Questions()
        {
            this.MVOC030Optionchoices = new HashSet<MVOC030Optionchoices>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string LangCode { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> CategoryLikePPPorJob { get; set; }
        public int Input_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVOC030Optionchoices> MVOC030Optionchoices { get; set; }
    }
}
