//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVOC030Optionchoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVOC030Optionchoices()
        {
            this.MVOC040QuestionOptions = new HashSet<MVOC040QuestionOptions>();
        }
    
        public long Id { get; set; }
        public Nullable<long> QuesId { get; set; }
        public string LangCode { get; set; }
        public string OptionText { get; set; }
        public Nullable<int> OptionTypeRdDdRefTypeId { get; set; }
    
        public virtual MVOC010Questions MVOC010Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVOC040QuestionOptions> MVOC040QuestionOptions { get; set; }
    }
}
