//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAV000OrderMapping
    {
        public int OrderMappingId { get; set; }
        public string M4PLColumn { get; set; }
        public string NavColumn { get; set; }
        public string TableName { get; set; }
        public string EntityName { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> SpecialHandling { get; set; }
    }
}
