//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAV000JobSalesOrderMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAV000JobSalesOrderMapping()
        {
            this.NAV000JobPurchaseOrderMapping = new HashSet<NAV000JobPurchaseOrderMapping>();
        }
    
        public long JobSalesOrderMappingId { get; set; }
        public long JobId { get; set; }
        public string SONumber { get; set; }
        public bool IsElectronicInvoiced { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
    
        public virtual JOBDL000Master JOBDL000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAV000JobPurchaseOrderMapping> NAV000JobPurchaseOrderMapping { get; set; }
    }
}
