//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAN020Financial_Cal
    {
        public long Id { get; set; }
        public Nullable<long> OrgID { get; set; }
        public Nullable<int> FclPeriod { get; set; }
        public string FclPeriodCode { get; set; }
        public Nullable<System.DateTime> FclPeriodStart { get; set; }
        public Nullable<System.DateTime> FclPeriodEnd { get; set; }
        public string FclPeriodTitle { get; set; }
        public string FclAutoShortCode { get; set; }
        public Nullable<int> FclWorkDays { get; set; }
        public Nullable<int> FinCalendarTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public byte[] FclDescription { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
