//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAN022Act_SubSecurityByRole
    {
        public long Id { get; set; }
        public Nullable<long> OrgSecurityByRoleId { get; set; }
        public string RefTableName { get; set; }
        public Nullable<int> SubsMenuOptionLevelId { get; set; }
        public Nullable<int> SubsMenuAccessLevelId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ORGAN021Act_SecurityByRole ORGAN021Act_SecurityByRole { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
    }
}
