//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAN000Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGAN000Master()
        {
            this.COMP000Master = new HashSet<COMP000Master>();
            this.CONTC000Master = new HashSet<CONTC000Master>();
            this.CONTC010Bridge = new HashSet<CONTC010Bridge>();
            this.CUST000Master = new HashSet<CUST000Master>();
            this.CUST020BusinessTerms = new HashSet<CUST020BusinessTerms>();
            this.CUST030DocumentReference = new HashSet<CUST030DocumentReference>();
            this.CUST050Finacial_Cal = new HashSet<CUST050Finacial_Cal>();
            this.MVOC000Program = new HashSet<MVOC000Program>();
            this.ORGAN002MRKT_OrgSupport = new HashSet<ORGAN002MRKT_OrgSupport>();
            this.ORGAN010Ref_Roles = new HashSet<ORGAN010Ref_Roles>();
            this.ORGAN020Financial_Cal = new HashSet<ORGAN020Financial_Cal>();
            this.ORGAN030Credentials = new HashSet<ORGAN030Credentials>();
            this.ORGAN040_Roles = new HashSet<ORGAN040_Roles>();
            this.PRGRM000Master = new HashSet<PRGRM000Master>();
            this.PRGRM020_Roles = new HashSet<PRGRM020_Roles>();
            this.PRGRM020Program_Role = new HashSet<PRGRM020Program_Role>();
            this.PRGRM030ShipStatusReasonCodes = new HashSet<PRGRM030ShipStatusReasonCodes>();
            this.PRGRM031ShipApptmtReasonCodes = new HashSet<PRGRM031ShipApptmtReasonCodes>();
            this.SYSTM000Delivery_Status = new HashSet<SYSTM000Delivery_Status>();
            this.SYSTM000OpnSezMe = new HashSet<SYSTM000OpnSezMe>();
            this.SYSTM000Ref_Dashboard = new HashSet<SYSTM000Ref_Dashboard>();
            this.SYSTM000Ref_Report = new HashSet<SYSTM000Ref_Report>();
            this.SYSTM000Ref_UserSettings = new HashSet<SYSTM000Ref_UserSettings>();
            this.VEND000Master = new HashSet<VEND000Master>();
            this.VEND020BusinessTerms = new HashSet<VEND020BusinessTerms>();
            this.VEND030DocumentReference = new HashSet<VEND030DocumentReference>();
            this.VEND050Finacial_Cal = new HashSet<VEND050Finacial_Cal>();
        }
    
        public long Id { get; set; }
        public string OrgCode { get; set; }
        public string OrgTitle { get; set; }
        public Nullable<int> OrgGroupId { get; set; }
        public Nullable<int> OrgSortOrder { get; set; }
        public byte[] OrgDescription { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<long> OrgContactId { get; set; }
        public byte[] OrgImage { get; set; }
        public Nullable<long> OrgWorkAddressId { get; set; }
        public Nullable<long> OrgBusinessAddressId { get; set; }
        public Nullable<long> OrgCorporateAddressId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMP000Master> COMP000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTC000Master> CONTC000Master { get; set; }
        public virtual CONTC000Master CONTC000Master1 { get; set; }
        public virtual CONTC000Master CONTC000Master2 { get; set; }
        public virtual CONTC000Master CONTC000Master3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTC010Bridge> CONTC010Bridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST000Master> CUST000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST020BusinessTerms> CUST020BusinessTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST030DocumentReference> CUST030DocumentReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST050Finacial_Cal> CUST050Finacial_Cal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVOC000Program> MVOC000Program { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN002MRKT_OrgSupport> ORGAN002MRKT_OrgSupport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN010Ref_Roles> ORGAN010Ref_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN020Financial_Cal> ORGAN020Financial_Cal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN030Credentials> ORGAN030Credentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN040_Roles> ORGAN040_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM000Master> PRGRM000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM020_Roles> PRGRM020_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM020Program_Role> PRGRM020Program_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM030ShipStatusReasonCodes> PRGRM030ShipStatusReasonCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM031ShipApptmtReasonCodes> PRGRM031ShipApptmtReasonCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Delivery_Status> SYSTM000Delivery_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000OpnSezMe> SYSTM000OpnSezMe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Ref_Dashboard> SYSTM000Ref_Dashboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Ref_Report> SYSTM000Ref_Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Ref_UserSettings> SYSTM000Ref_UserSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND000Master> VEND000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND020BusinessTerms> VEND020BusinessTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND030DocumentReference> VEND030DocumentReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEND050Finacial_Cal> VEND050Finacial_Cal { get; set; }
    }
}
