//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAN021Act_SecurityByRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGAN021Act_SecurityByRole()
        {
            this.ORGAN022Act_SubSecurityByRole = new HashSet<ORGAN022Act_SubSecurityByRole>();
        }
    
        public long Id { get; set; }
        public long OrgId { get; set; }
        public long OrgActRoleId { get; set; }
        public long ContactId { get; set; }
        public Nullable<int> SecLineOrder { get; set; }
        public Nullable<int> SecMainModuleId { get; set; }
        public Nullable<int> SecMenuOptionLevelId { get; set; }
        public Nullable<int> SecMenuAccessLevelId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN022Act_SubSecurityByRole> ORGAN022Act_SubSecurityByRole { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual ORGAN020Act_Roles ORGAN020Act_Roles { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
    }
}
