//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAN001POC_Contacts
    {
        public long Id { get; set; }
        public Nullable<long> OrgID { get; set; }
        public Nullable<long> ContactID { get; set; }
        public Nullable<int> PocSortOrder { get; set; }
        public string PocCode { get; set; }
        public string PocTitle { get; set; }
        public Nullable<int> PocTypeId { get; set; }
        public byte[] PocDescription { get; set; }
        public byte[] PocInstructions { get; set; }
        public Nullable<bool> PocDefault { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
