//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM071EdiMapping
    {
        public long Id { get; set; }
        public Nullable<long> PemHeaderID { get; set; }
        public string PemEdiTableName { get; set; }
        public string PemEdiFieldName { get; set; }
        public string PemEdiFieldDataType { get; set; }
        public string PemSysTableName { get; set; }
        public string PemSysFieldName { get; set; }
        public string PemSysFieldDataType { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PemInsertUpdate { get; set; }
        public Nullable<System.DateTime> PemDateStart { get; set; }
        public Nullable<System.DateTime> PemDateEnd { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual PRGRM070EdiHeader PRGRM070EdiHeader { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
