//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM010Ref_GatewayDefaults
    {
        public long Id { get; set; }
        public Nullable<int> PgdGatewaySortOrder { get; set; }
        public string PgdGatewayCode { get; set; }
        public string PgdGatewayTitle { get; set; }
        public byte[] PgdGatewayDescription { get; set; }
        public Nullable<decimal> PgdGatewayDuration { get; set; }
        public Nullable<bool> PgdGatewayDefault { get; set; }
        public Nullable<bool> Scanner { get; set; }
        public string PgdShipStatusReasonCode { get; set; }
        public string PgdShipApptmtReasonCode { get; set; }
        public string PgdOrderType { get; set; }
        public string PgdShipmentType { get; set; }
        public byte[] PgdGatewayComment { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<bool> PgdGatewayDefaultComplete { get; set; }
        public string MappingId { get; set; }
        public string PgdGatewayStatusCode { get; set; }
        public Nullable<bool> PgdGatewayDefaultForJob { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual CONTC000Master CONTC000Master1 { get; set; }
        public virtual JOBDL023GatewayInstallStatusMaster JOBDL023GatewayInstallStatusMaster { get; set; }
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options4 { get; set; }
    }
}
