//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM020Program_Role
    {
        public long Id { get; set; }
        public Nullable<int> PrgRoleSortOrder { get; set; }
        public string PrgRoleTitle { get; set; }
        public Nullable<bool> PrxJobDefaultAnalyst { get; set; }
        public Nullable<bool> PrxJobDefaultResponsible { get; set; }
        public Nullable<bool> PrxJobGWDefaultAnalyst { get; set; }
        public Nullable<bool> PrxJobGWDefaultResponsible { get; set; }
        public byte[] PrgRoleDescription { get; set; }
        public byte[] PrgComments { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual ORGAN010Ref_Roles ORGAN010Ref_Roles { get; set; }
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual PRGRM020_Roles PRGRM020_Roles { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
