//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM020Ref_AttributesDefault
    {
        public long Id { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<int> AttItemNumber { get; set; }
        public string AttCode { get; set; }
        public string AttTitle { get; set; }
        public byte[] AttDescription { get; set; }
        public byte[] AttComments { get; set; }
        public Nullable<int> AttQuantity { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public Nullable<bool> AttDefault { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
