//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM042ProgramBillableLocations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRGRM042ProgramBillableLocations()
        {
            this.PRGRM040ProgramBillableRate = new HashSet<PRGRM040ProgramBillableRate>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PblProgramID { get; set; }
        public Nullable<long> PblVendorID { get; set; }
        public Nullable<int> PblItemNumber { get; set; }
        public string PblLocationCode { get; set; }
        public string PblLocationCodeVendor { get; set; }
        public string PblLocationTitle { get; set; }
        public string PblUserCode1 { get; set; }
        public string PblUserCode2 { get; set; }
        public string PblUserCode3 { get; set; }
        public string PblUserCode4 { get; set; }
        public string PblUserCode5 { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public int StatusId { get; set; }
        public Nullable<long> PblVenderLocationId { get; set; }
        public Nullable<long> PblVenderDCLocationId { get; set; }
    
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRGRM040ProgramBillableRate> PRGRM040ProgramBillableRate { get; set; }
        public virtual VEND000Master VEND000Master { get; set; }
    }
}
