//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM041ProgramCostRate
    {
        public long Id { get; set; }
        public string PcrCode { get; set; }
        public string PcrVendorCode { get; set; }
        public Nullable<System.DateTime> PcrEffectiveDate { get; set; }
        public string PcrTitle { get; set; }
        public Nullable<int> RateCategoryTypeId { get; set; }
        public Nullable<int> RateTypeId { get; set; }
        public Nullable<decimal> PcrCostRate { get; set; }
        public Nullable<int> RateUnitTypeId { get; set; }
        public string PcrFormat { get; set; }
        public byte[] PcrDescription { get; set; }
        public string PcrExpression01 { get; set; }
        public string PcrLogic01 { get; set; }
        public string PcrExpression02 { get; set; }
        public string PcrLogic02 { get; set; }
        public string PcrExpression03 { get; set; }
        public string PcrLogic03 { get; set; }
        public string PcrExpression04 { get; set; }
        public string PcrLogic04 { get; set; }
        public string PcrExpression05 { get; set; }
        public string PcrLogic05 { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<long> PcrCustomerID { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<long> ProgramLocationId { get; set; }
    
        public virtual CUST000Master CUST000Master { get; set; }
        public virtual PRGRM043ProgramCostLocations PRGRM043ProgramCostLocations { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
    }
}
