//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRGRM040ProgramBillableRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRGRM040ProgramBillableRate()
        {
            this.JOBDL061BillableSheet = new HashSet<JOBDL061BillableSheet>();
        }
    
        public long Id { get; set; }
        public string PbrCode { get; set; }
        public string PbrCustomerCode { get; set; }
        public Nullable<System.DateTime> PbrEffectiveDate { get; set; }
        public string PbrTitle { get; set; }
        public Nullable<decimal> PbrBillablePrice { get; set; }
        public string PbrFormat { get; set; }
        public byte[] PbrDescription { get; set; }
        public string PbrExpression01 { get; set; }
        public string PbrLogic01 { get; set; }
        public string PbrExpression02 { get; set; }
        public string PbrLogic02 { get; set; }
        public string PbrExpression03 { get; set; }
        public string PbrLogic03 { get; set; }
        public string PbrExpression04 { get; set; }
        public string PbrLogic04 { get; set; }
        public string PbrExpression05 { get; set; }
        public string PbrLogic05 { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public bool PbrElectronicBilling { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDL061BillableSheet> JOBDL061BillableSheet { get; set; }
        public virtual PRGRM042ProgramBillableLocations PRGRM042ProgramBillableLocations { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
        public virtual VEND040DCLocations VEND040DCLocations { get; set; }
    }
}
