//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN006CargoDetail
    {
        public long CargoDetailID { get; set; }
        public Nullable<long> CargoID { get; set; }
        public string DetSerialNumber { get; set; }
        public Nullable<decimal> DetQtyCounted { get; set; }
        public Nullable<decimal> DetQtyDamaged { get; set; }
        public Nullable<decimal> DetQtyShort { get; set; }
        public Nullable<decimal> DetQtyOver { get; set; }
        public string DetPickStatus { get; set; }
        public string DetLong { get; set; }
        public string DetLat { get; set; }
    }
}
