//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN013OrderServicesPhoto
    {
        public Nullable<long> ServicesID { get; set; }
        public string ServiceIDText { get; set; }
        public Nullable<long> JobID { get; set; }
        public string JobIDText { get; set; }
        public byte[] Photo { get; set; }
    }
}
