//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN007CargoBCPhoto
    {
        public Nullable<long> CargoID { get; set; }
        public string CargoIDText { get; set; }
        public byte[] Photo { get; set; }
        public string Step { get; set; }
    }
}
