//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN016DriverList
    {
        public long DriverID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public string LocationNumber { get; set; }
    }
}
