//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN014OrderOSD
    {
        public long CargoOSDID { get; set; }
        public Nullable<long> OSDID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CargoDetailID { get; set; }
        public Nullable<long> CargoID { get; set; }
        public string CgoSerialNumber { get; set; }
        public Nullable<long> OSDReasonID { get; set; }
        public Nullable<decimal> OSDQty { get; set; }
        public string Notes { get; set; }
        public string EditCD { get; set; }
        public string StatusID { get; set; }
        public string CgoSeverityCode { get; set; }
    }
}
