//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN005Cargo
    {
        public long CargoID { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<int> CgoLineItem { get; set; }
        public string CgoPartNumCode { get; set; }
        public Nullable<decimal> CgoQtyOrdered { get; set; }
        public Nullable<decimal> CgoQtyExpected { get; set; }
        public Nullable<decimal> CgoQtyCounted { get; set; }
        public Nullable<decimal> CgoQtyDamaged { get; set; }
        public Nullable<decimal> CgoQtyOnHold { get; set; }
        public Nullable<decimal> CgoQtyShort { get; set; }
        public Nullable<decimal> CgoQtyOver { get; set; }
        public string CgoQtyUnits { get; set; }
        public string CgoStatus { get; set; }
        public string CgoInfoID { get; set; }
        public Nullable<int> ColorCD { get; set; }
        public string CgoSerialCD { get; set; }
        public string CgoLong { get; set; }
        public string CgoLat { get; set; }
        public string CgoMasterLabel { get; set; }
        public string CgoProFlag01 { get; set; }
        public string CgoProFlag02 { get; set; }
        public string CgoProFlag03 { get; set; }
        public string CgoProFlag04 { get; set; }
        public string CgoProFlag05 { get; set; }
        public string CgoProFlag06 { get; set; }
        public string CgoProFlag07 { get; set; }
        public string CgoProFlag08 { get; set; }
        public string CgoProFlag09 { get; set; }
        public string CgoProFlag10 { get; set; }
        public string CgoProFlag11 { get; set; }
        public string CgoProFlag12 { get; set; }
        public string CgoProFlag13 { get; set; }
        public string CgoProFlag14 { get; set; }
        public string CgoProFlag15 { get; set; }
        public string CgoProFlag16 { get; set; }
        public string CgoProFlag17 { get; set; }
        public string CgoProFlag18 { get; set; }
        public string CgoProFlag19 { get; set; }
        public string CgoProFlag20 { get; set; }
    }
}
