//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCN000Order
    {
        public long JobID { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<long> DriverID { get; set; }
        public string JobDeviceID { get; set; }
        public Nullable<int> JobStop { get; set; }
        public string JobOrderID { get; set; }
        public string JobManifestID { get; set; }
        public string JobCarrierID { get; set; }
        public Nullable<int> JobReturnReasonID { get; set; }
        public string JobStatusCD { get; set; }
        public string JobOriginSiteCode { get; set; }
        public string JobOriginSiteName { get; set; }
        public string JobDeliverySitePOC { get; set; }
        public string JobDeliverySitePOC2 { get; set; }
        public string JobDeliveryStreetAddress { get; set; }
        public string JobDeliveryStreetAddress2 { get; set; }
        public string JobDeliveryCity { get; set; }
        public string JobDeliveryStateProvince { get; set; }
        public string JobDeliveryPostalCode { get; set; }
        public string JobDeliveryCountry { get; set; }
        public string JobDeliverySitePOCPhone { get; set; }
        public string JobDeliverySitePOCPhone2 { get; set; }
        public string JobDeliveryPhoneHm { get; set; }
        public string JobDeliverySitePOCEmail { get; set; }
        public string JobDeliverySitePOCEmail2 { get; set; }
        public string JobOriginStreetAddress { get; set; }
        public string JobOriginCity { get; set; }
        public string JobOriginStateProvince { get; set; }
        public string JobOriginPostalCode { get; set; }
        public string JobOriginCountry { get; set; }
        public string JobLongitude { get; set; }
        public string JobLatitude { get; set; }
        public string JobSignLongitude { get; set; }
        public string JobSignLatitude { get; set; }
        public string JobSignText { get; set; }
        public byte[] JobSignCapture { get; set; }
        public Nullable<System.DateTime> JobScheduledDate { get; set; }
        public Nullable<System.DateTime> JobScheduledTime { get; set; }
        public Nullable<System.DateTime> JobEstimatedDate { get; set; }
        public Nullable<System.DateTime> JobEstimatedTime { get; set; }
        public Nullable<System.DateTime> JobActualDate { get; set; }
        public Nullable<System.DateTime> JobActualTime { get; set; }
        public Nullable<int> ColorCD { get; set; }
        public string JobFor { get; set; }
        public string JobFrom { get; set; }
        public Nullable<System.DateTime> WindowStartTime { get; set; }
        public Nullable<System.DateTime> WindowEndTime { get; set; }
        public string JobFlag01 { get; set; }
        public string JobFlag02 { get; set; }
        public string JobFlag03 { get; set; }
        public string JobFlag04 { get; set; }
        public string JobFlag05 { get; set; }
        public string JobFlag06 { get; set; }
        public string JobFlag07 { get; set; }
        public string JobFlag08 { get; set; }
        public string JobFlag09 { get; set; }
        public string JobFlag10 { get; set; }
        public string JobFlag11 { get; set; }
        public string JobFlag12 { get; set; }
        public string JobFlag13 { get; set; }
        public string JobFlag14 { get; set; }
        public string JobFlag15 { get; set; }
        public string JobFlag16 { get; set; }
        public string JobFlag17 { get; set; }
        public string JobFlag18 { get; set; }
        public string JobFlag19 { get; set; }
        public string JobFlag20 { get; set; }
        public Nullable<int> JobFlag21 { get; set; }
        public Nullable<long> JobFlag22 { get; set; }
        public Nullable<int> JobFlag23 { get; set; }
    }
}
