//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCR011OSDList
    {
        public long OSDID { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<int> OSDItemNumber { get; set; }
        public string OSDCode { get; set; }
        public string OSDTitle { get; set; }
        public string OSDType { get; set; }
        public string OSDNote { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
