//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCR013ServiceList
    {
        public long ServiceID { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<int> ServiceLineItem { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceTitle { get; set; }
        public byte[] ServiceDescription { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
