//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCR010CatalogList
    {
        public long Id { get; set; }
        public string IdText { get; set; }
        public Nullable<long> CatalogProgramID { get; set; }
        public string CatalogProgramIDText { get; set; }
        public Nullable<int> CatalogItemNumber { get; set; }
        public string CatalogCode { get; set; }
        public string CatalogCustCode { get; set; }
        public string CatalogTitle { get; set; }
        public string CatalogDesc { get; set; }
        public byte[] CatalogPhoto { get; set; }
        public string CatalogUoMCode { get; set; }
        public Nullable<decimal> CatalogCubes { get; set; }
        public Nullable<decimal> CatalogWidth { get; set; }
        public Nullable<decimal> CatalogLength { get; set; }
        public Nullable<decimal> CatalogHeight { get; set; }
        public string CatalogWeight { get; set; }
        public string CatalogWLHUoM { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
