//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTPServerDetail
    {
        public int ID { get; set; }
        public string SMTPServerName { get; set; }
        public int SMTPServerPort { get; set; }
        public string SMTPLoginUserName { get; set; }
        public string SMTPLoginPassword { get; set; }
        public bool IsSSLEnabled { get; set; }
        public string DefaultFromAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
