//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SummaryHeader()
        {
            this.Addresses = new HashSet<Address>();
            this.CustomAttributes = new HashSet<CustomAttribute>();
            this.LineDetails = new HashSet<LineDetail>();
            this.UserDefinedFields = new HashSet<UserDefinedField>();
        }
    
        public long SummaryHeaderId { get; set; }
        public string TradingPartner { get; set; }
        public Nullable<long> GroupControlNo { get; set; }
        public string BOLNo { get; set; }
        public string MasterBOLNo { get; set; }
        public string MethodOfPayment { get; set; }
        public string SetPurpose { get; set; }
        public string CustomerReferenceNo { get; set; }
        public string ShipDescription { get; set; }
        public string OrderType { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate3PL { get; set; }
        public string ServiceMode { get; set; }
        public string ProductType { get; set; }
        public string ReasonCodeCancellation { get; set; }
        public string ManifestNo { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> TotalCubicFeet { get; set; }
        public Nullable<long> TotalPieces { get; set; }
        public string DeliveryCommitmentType { get; set; }
        public Nullable<System.DateTime> ScheduledPickupDate { get; set; }
        public Nullable<System.DateTime> ScheduledDeliveryDate { get; set; }
        public string SpecialNotes { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public string TextData { get; set; }
        public string LocationId { get; set; }
        public string LocationNumber { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool isxcblAcceptanceRequired { get; set; }
        public bool isxcblProcessed { get; set; }
        public bool isxcblRejected { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public string Action { get; set; }
        public string TrailerNumber { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomAttribute> CustomAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineDetail> LineDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDefinedField> UserDefinedFields { get; set; }
    }
}
