//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVYUSER000Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SVYUSER000Master()
        {
            this.SVYANS000Master = new HashSet<SVYANS000Master>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string EntityTypeId { get; set; }
        public string EntityType { get; set; }
        public Nullable<long> UserId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string Feedback { get; set; }
        public Nullable<long> SurveyId { get; set; }
        public string LocationCode { get; set; }
        public string DriverId { get; set; }
        public string ContractNumber { get; set; }
        public string CustName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SVYANS000Master> SVYANS000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
