//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys000AuditTrail
    {
        public long EntityId { get; set; }
        public string EntityType { get; set; }
        public int EntityTypeId { get; set; }
        public string OrigionalData { get; set; }
        public string ChangedData { get; set; }
        public Nullable<long> ChangedByUserId { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
    }
}
