//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000OpnSezMe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTM000OpnSezMe()
        {
            this.AUTH020_Token = new HashSet<AUTH020_Token>();
            this.AUTH030_LoginProvider = new HashSet<AUTH030_LoginProvider>();
            this.AUTH050_UserPassword = new HashSet<AUTH050_UserPassword>();
            this.SYSTM000Ref_UserSettings = new HashSet<SYSTM000Ref_UserSettings>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SysUserContactID { get; set; }
        public string SysScreenName { get; set; }
        public string SysPassword { get; set; }
        public byte[] SysComments { get; set; }
        public Nullable<long> SysOrgId { get; set; }
        public Nullable<long> SysOrgRefRoleId { get; set; }
        public bool IsSysAdmin { get; set; }
        public int SysAttempts { get; set; }
        public Nullable<bool> SysLoggedIn { get; set; }
        public Nullable<int> SysLoggedInCount { get; set; }
        public Nullable<System.DateTime> SysDateLastAttempt { get; set; }
        public Nullable<System.DateTime> SysLoggedInStart { get; set; }
        public Nullable<System.DateTime> SysLoggedInEnd { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual CONTC000Master CONTC000Master { get; set; }
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual ORGAN010Ref_Roles ORGAN010Ref_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH020_Token> AUTH020_Token { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH030_LoginProvider> AUTH030_LoginProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH050_UserPassword> AUTH050_UserPassword { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Ref_UserSettings> SYSTM000Ref_UserSettings { get; set; }
    }
}
