//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000ColumnSettingsByUser
    {
        public long Id { get; set; }
        public Nullable<long> ColUserId { get; set; }
        public string ColSortOrder { get; set; }
        public string ColNotVisible { get; set; }
        public string ColIsFreezed { get; set; }
        public string ColIsDefault { get; set; }
        public string ColGroupBy { get; set; }
        public string ColGridLayout { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
        public string ColMask { get; set; }
    
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
    }
}
