//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000ZipcodeMaster
    {
        public string Zipcode { get; set; }
        public string ZipCity { get; set; }
        public string ZipState { get; set; }
        public Nullable<double> ZipLatitude { get; set; }
        public Nullable<double> ZipLongitude { get; set; }
        public Nullable<double> ZipTimezone { get; set; }
        public Nullable<double> ZipDST { get; set; }
        public Nullable<long> MrktID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ORGAN002MRKT_OrgSupport ORGAN002MRKT_OrgSupport { get; set; }
    }
}
