//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000ColumnsAlias
    {
        public long Id { get; set; }
        public string LangCode { get; set; }
        public string ColTableName { get; set; }
        public string ColAssociatedTableName { get; set; }
        public string ColColumnName { get; set; }
        public string ColAliasName { get; set; }
        public string ColCaption { get; set; }
        public Nullable<int> ColLookupId { get; set; }
        public string ColLookupCode { get; set; }
        public string ColDescription { get; set; }
        public Nullable<int> ColSortOrder { get; set; }
        public Nullable<bool> ColIsReadOnly { get; set; }
        public bool ColIsVisible { get; set; }
        public bool ColIsDefault { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ColDisplayFormat { get; set; }
        public Nullable<bool> ColAllowNegativeValue { get; set; }
        public bool ColIsGroupBy { get; set; }
        public string ColMask { get; set; }
        public Nullable<bool> IsGridColumn { get; set; }
        public string ColGridAliasName { get; set; }
    }
}
