//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000MenuDriver
    {
        public long Id { get; set; }
        public string LangCode { get; set; }
        public string MnuBreakDownStructure { get; set; }
        public string MnuTitle { get; set; }
        public byte[] MnuDescription { get; set; }
        public string MnuTabOver { get; set; }
        public Nullable<bool> MnuMenuItem { get; set; }
        public Nullable<bool> MnuRibbon { get; set; }
        public string MnuRibbonTabName { get; set; }
        public byte[] MnuIconVerySmall { get; set; }
        public byte[] MnuIconSmall { get; set; }
        public byte[] MnuIconMedium { get; set; }
        public byte[] MnuIconLarge { get; set; }
        public string MnuExecuteProgram { get; set; }
        public byte[] MnuHelpFile { get; set; }
        public string MnuHelpBookMark { get; set; }
        public Nullable<int> MnuHelpPageNumber { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options4 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options5 { get; set; }
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
    }
}
