//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000Master
    {
        public long Id { get; set; }
        public string LangCode { get; set; }
        public string SysMessageCode { get; set; }
        public int SysRefId { get; set; }
        public string SysMessageScreenTitle { get; set; }
        public string SysMessageTitle { get; set; }
        public string SysMessageDescription { get; set; }
        public string SysMessageInstruction { get; set; }
        public string SysMessageButtonSelection { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
