//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000Ref_Lookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTM000Ref_Lookup()
        {
            this.SYSTM000Ref_Options = new HashSet<SYSTM000Ref_Options>();
        }
    
        public int Id { get; set; }
        public string LkupCode { get; set; }
        public string LkupTableName { get; set; }
    
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Ref_Options> SYSTM000Ref_Options { get; set; }
    }
}
