//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM020Ref_Attachments
    {
        public long Id { get; set; }
        public Nullable<long> AttPrimaryRecordID { get; set; }
        public Nullable<int> AttItemNumber { get; set; }
        public string AttTitle { get; set; }
        public Nullable<int> AttTypeId { get; set; }
        public string AttFileName { get; set; }
        public byte[] AttData { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
        public string AttDownloadDate { get; set; }
        public Nullable<System.DateTime> AttDownloadedDate { get; set; }
        public string AttDownloadedBy { get; set; }
    
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
    }
}
