//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000Ref_Settings
    {
        public long Id { get; set; }
        public Nullable<int> SysSessionTimeOut { get; set; }
        public Nullable<int> SysWarningTime { get; set; }
        public Nullable<int> SysMainModuleId { get; set; }
        public string SysDefaultAction { get; set; }
        public string SysStatusesIn { get; set; }
        public string SysGridViewPageSizes { get; set; }
        public Nullable<int> SysPageSize { get; set; }
        public Nullable<int> SysComboBoxPageSize { get; set; }
        public Nullable<int> SysThresholdPercentage { get; set; }
        public string SysDateFormat { get; set; }
    
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
    }
}
