//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000_StatusLog
    {
        public long Id { get; set; }
        public Nullable<long> ProgramID { get; set; }
        public Nullable<long> JobID { get; set; }
        public string SiteName { get; set; }
        public Nullable<long> GatewayID { get; set; }
        public string GatewayCode { get; set; }
        public string GatewayType { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> SeverityId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual JOBDL000Master JOBDL000Master { get; set; }
        public virtual PRGRM000Master PRGRM000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
    }
}
