//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM041ProcessorErrorLog
    {
        public long Id { get; set; }
        public string PelProcessorName { get; set; }
        public Nullable<int> PelPriority { get; set; }
        public string PelSourceTable { get; set; }
        public string PelSourceId { get; set; }
        public string PelInnerException { get; set; }
        public string PelMessage { get; set; }
        public string PelMethod { get; set; }
        public string PelStackTrace { get; set; }
        public string PelAdditionalMessage { get; set; }
        public System.DateTime PelDateStamp { get; set; }
    }
}
