//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM030Ref_TabPageName
    {
        public long Id { get; set; }
        public string LangCode { get; set; }
        public string RefTableName { get; set; }
        public Nullable<int> TabSortOrder { get; set; }
        public string TabTableName { get; set; }
        public string TabPageTitle { get; set; }
        public string TabExecuteProgram { get; set; }
        public byte[] TabPageIcon { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table { get; set; }
        public virtual SYSTM000Ref_Table SYSTM000Ref_Table1 { get; set; }
    }
}
