//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000SecurityByRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTM000SecurityByRole()
        {
            this.SYSTM010SubSecurityByRole = new HashSet<SYSTM010SubSecurityByRole>();
        }
    
        public long Id { get; set; }
        public long OrgRefRoleId { get; set; }
        public Nullable<int> SecLineOrder { get; set; }
        public Nullable<int> SecMainModuleId { get; set; }
        public Nullable<int> SecMenuOptionLevelId { get; set; }
        public Nullable<int> SecMenuAccessLevelId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ORGAN010Ref_Roles ORGAN010Ref_Roles { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM010SubSecurityByRole> SYSTM010SubSecurityByRole { get; set; }
    }
}
