//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM000Ref_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTM000Ref_Table()
        {
            this.CONTC010Bridge = new HashSet<CONTC010Bridge>();
            this.SYSTM000ColumnsAlias = new HashSet<SYSTM000ColumnsAlias>();
            this.SYSTM000ColumnSettingsByUser = new HashSet<SYSTM000ColumnSettingsByUser>();
            this.SYSTM000MenuDriver = new HashSet<SYSTM000MenuDriver>();
            this.SYSTM000Ref_Lookup = new HashSet<SYSTM000Ref_Lookup>();
            this.SYSTM000Validation = new HashSet<SYSTM000Validation>();
            this.SYSTM010SubSecurityByRole = new HashSet<SYSTM010SubSecurityByRole>();
            this.SYSTM020Ref_Attachments = new HashSet<SYSTM020Ref_Attachments>();
            this.SYSTM030Ref_TabPageName = new HashSet<SYSTM030Ref_TabPageName>();
            this.SYSTM030Ref_TabPageName1 = new HashSet<SYSTM030Ref_TabPageName>();
        }
    
        public string SysRefName { get; set; }
        public string LangCode { get; set; }
        public string TblLangName { get; set; }
        public string TblTableName { get; set; }
        public Nullable<int> TblMainModuleId { get; set; }
        public byte[] TblIcon { get; set; }
        public Nullable<int> TblTypeId { get; set; }
        public string TblPrimaryKeyName { get; set; }
        public string TblParentIdFieldName { get; set; }
        public string TblItemNumberFieldName { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTC010Bridge> CONTC010Bridge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000ColumnsAlias> SYSTM000ColumnsAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000ColumnSettingsByUser> SYSTM000ColumnSettingsByUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000MenuDriver> SYSTM000MenuDriver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Ref_Lookup> SYSTM000Ref_Lookup { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM000Validation> SYSTM000Validation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM010SubSecurityByRole> SYSTM010SubSecurityByRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM020Ref_Attachments> SYSTM020Ref_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM030Ref_TabPageName> SYSTM030Ref_TabPageName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTM030Ref_TabPageName> SYSTM030Ref_TabPageName1 { get; set; }
    }
}
