//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTM040ProcessorConfig
    {
        public long ID { get; set; }
        public Nullable<long> PrcProcessorID { get; set; }
        public string PrcConfigKey { get; set; }
        public string PrcConfigValue { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual SYSTM000ProcessorMaster SYSTM000ProcessorMaster { get; set; }
    }
}
