//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEND020BusinessTerms
    {
        public long Id { get; set; }
        public string LangCode { get; set; }
        public Nullable<int> VbtItemNumber { get; set; }
        public string VbtCode { get; set; }
        public string VbtTitle { get; set; }
        public byte[] VbtDescription { get; set; }
        public Nullable<System.DateTime> VbtActiveDate { get; set; }
        public Nullable<decimal> VbtValue { get; set; }
        public Nullable<decimal> VbtHiThreshold { get; set; }
        public Nullable<decimal> VbtLoThreshold { get; set; }
        public Nullable<int> VbtAttachment { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual VEND000Master VEND000Master { get; set; }
    }
}
