//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEND030DocumentReference
    {
        public long Id { get; set; }
        public Nullable<int> VdrItemNumber { get; set; }
        public string VdrCode { get; set; }
        public string VdrTitle { get; set; }
        public byte[] VdrDescription { get; set; }
        public Nullable<int> VdrAttachment { get; set; }
        public Nullable<System.DateTime> VdrDateStart { get; set; }
        public Nullable<System.DateTime> VdrDateEnd { get; set; }
        public Nullable<bool> VdrRenewal { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual ORGAN000Master ORGAN000Master { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options1 { get; set; }
        public virtual SYSTM000Ref_Options SYSTM000Ref_Options2 { get; set; }
        public virtual VEND000Master VEND000Master { get; set; }
    }
}
