//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDCLocationContactMapping
    {
        public long Id { get; set; }
        public Nullable<long> ContactMSTRID { get; set; }
        public string ConTableName { get; set; }
        public long ConOrgId { get; set; }
        public Nullable<long> ConPrimaryRecordId { get; set; }
        public Nullable<int> ConItemNumber { get; set; }
        public string ConTitle { get; set; }
        public Nullable<long> ConCodeId { get; set; }
        public Nullable<int> ConTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> ConIsDefault { get; set; }
        public byte[] ConDescription { get; set; }
        public byte[] ConInstruction { get; set; }
        public Nullable<int> ConTableTypeId { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public long ContactMasterID { get; set; }
        public string ConERPId { get; set; }
        public Nullable<long> ConCompanyId { get; set; }
        public string ConCompanyName { get; set; }
        public string ConLastName { get; set; }
        public string ConFirstName { get; set; }
        public string ConMiddleName { get; set; }
        public string ConEmailAddress { get; set; }
        public string ConEmailAddress2 { get; set; }
        public string ConJobTitle { get; set; }
        public string ConBusinessPhone { get; set; }
        public string ConBusinessPhoneExt { get; set; }
        public string ConHomePhone { get; set; }
        public string ConMobilePhone { get; set; }
        public string ConFaxNumber { get; set; }
        public string ConBusinessAddress1 { get; set; }
        public string ConBusinessAddress2 { get; set; }
        public string ConBusinessCity { get; set; }
        public Nullable<int> ConBusinessStateId { get; set; }
        public string ConBusinessZipPostal { get; set; }
        public Nullable<int> ConBusinessCountryId { get; set; }
        public string ConHomeAddress1 { get; set; }
        public string ConHomeAddress2 { get; set; }
        public string ConHomeCity { get; set; }
        public Nullable<int> ConHomeStateId { get; set; }
        public string ConHomeZipPostal { get; set; }
        public Nullable<int> ConHomeCountryId { get; set; }
        public Nullable<int> ConAttachments { get; set; }
        public string ConWebPage { get; set; }
        public string ConNotes { get; set; }
        public string ConOutlookId { get; set; }
        public Nullable<int> ConUDF01 { get; set; }
        public string ConUDF02 { get; set; }
        public string ConUDF03 { get; set; }
        public string ConUDF04 { get; set; }
        public string ConUDF05 { get; set; }
        public Nullable<int> ConTitleId { get; set; }
        public string ConFullName { get; set; }
    }
}
