//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetVocReportData
    {
        public long Id { get; set; }
        public string Location { get; set; }
        public string Job_ID { get; set; }
        public string Driver { get; set; }
        public Nullable<int> Delivery_Satisfaction { get; set; }
        public Nullable<int> CSR_Professionalism { get; set; }
        public Nullable<int> Advance_Delivery_Time { get; set; }
        public Nullable<int> Driver_Professionalism { get; set; }
        public Nullable<int> Delivery_Team_Helpfulness { get; set; }
        public Nullable<int> Overall_Score { get; set; }
    }
}
