//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobAdvanceReport
    {
        public long Id { get; set; }
        public Nullable<long> ProgramId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustTitle { get; set; }
        public Nullable<System.DateTime> JobOrderedDate { get; set; }
        public string JobBOL { get; set; }
        public Nullable<System.DateTime> JobOriginDateTimePlanned { get; set; }
        public Nullable<System.DateTime> JobDeliveryDateTimePlanned { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string JobGatewayStatus { get; set; }
        public string JobCustomerSalesOrder { get; set; }
        public string JobManifestNo { get; set; }
        public string PlantIDCode { get; set; }
        public string JobSellerSiteName { get; set; }
        public string JobDeliverySiteName { get; set; }
        public string JobDeliveryStreetAddress { get; set; }
        public string JobDeliveryStreetAddress2 { get; set; }
        public string JobDeliveryCity { get; set; }
        public string JobDeliveryState { get; set; }
        public string JobDeliveryPostalCode { get; set; }
        public string JobDeliverySitePOC { get; set; }
        public string JobDeliverySitePOCPhone { get; set; }
        public string JobDeliverySitePOCPhone2 { get; set; }
        public string JobSellerSitePOCEmail { get; set; }
        public string JobServiceMode { get; set; }
        public Nullable<System.DateTime> JobOriginDateTimeActual { get; set; }
        public Nullable<System.DateTime> JobDeliveryDateTimeActual { get; set; }
        public string JobCustomerPurchaseOrder { get; set; }
        public Nullable<decimal> JobTotalCubes { get; set; }
        public Nullable<decimal> TotalParts { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public string Brand { get; set; }
        public string Destination { get; set; }
        public string ProductType { get; set; }
        public string Channel { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    }
}
