//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobGateway
    {
        public long ID { get; set; }
        public Nullable<long> JobID { get; set; }
        public string GwyOrderType { get; set; }
        public string GwyGatewayCode { get; set; }
        public Nullable<bool> GwyCompleted { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string GwyGatewayTitle { get; set; }
    }
}
