//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class XcblSummaryHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XcblSummaryHeader()
        {
            this.XcblSummaryDetails = new HashSet<XcblSummaryDetail>();
        }
    
        public long xcblHeaderID { get; set; }
        public string xcblTradingPartner { get; set; }
        public Nullable<long> xcblGroupControlNo { get; set; }
        public string xcblBOLNo { get; set; }
        public string xcblMasterBOLNo { get; set; }
        public string xcblMethodOfPayment { get; set; }
        public string xcblSetPurpose { get; set; }
        public string xcblCustomerReferenceNo { get; set; }
        public string xcblLocationId { get; set; }
        public string xcblShipDescription { get; set; }
        public string xcblOrderType { get; set; }
        public string xcblPurchaseOrderNo { get; set; }
        public string xcblLocationNumber { get; set; }
        public Nullable<System.DateTime> xcblShipDate { get; set; }
        public Nullable<System.DateTime> xcblArrivalDate3PL { get; set; }
        public string xcblServiceMode { get; set; }
        public string xcblProductType { get; set; }
        public string xcblLatitude { get; set; }
        public string xcblLongitude { get; set; }
        public string xcblReasonCodeCancellation { get; set; }
        public string xcblManifestNo { get; set; }
        public Nullable<decimal> xcblTotalWeight { get; set; }
        public Nullable<decimal> xcblTotalCubicFeet { get; set; }
        public Nullable<long> xcblTotalPieces { get; set; }
        public string xcblDeliveryCommitmentType { get; set; }
        public Nullable<System.DateTime> xcblScheduledPickupDate { get; set; }
        public Nullable<System.DateTime> xcblScheduledDeliveryDate { get; set; }
        public string xcblSpecialNotes { get; set; }
        public string xcblConsigneeName { get; set; }
        public Nullable<long> xcblConsigneeNameID { get; set; }
        public string xcblConsigneeAddress1 { get; set; }
        public string xcblConsigneeAddress2 { get; set; }
        public string xcblConsigneeCity { get; set; }
        public string xcblConsigneeState { get; set; }
        public string xcblConsigneePostalCode { get; set; }
        public string xcblConsigneeCountryCode { get; set; }
        public string xcblConsigneeContactName { get; set; }
        public string xcblConsigneeContactNumber { get; set; }
        public string xcblConsigneeAltContName { get; set; }
        public string xcblConsigneeAltContNumber { get; set; }
        public string xcblInterConsigneeName { get; set; }
        public Nullable<long> xcblInterConsigneeNameID { get; set; }
        public string xcblInterConsigneeAddress1 { get; set; }
        public string xcblInterConsigneeAddress2 { get; set; }
        public string xcblInterConsigneeCity { get; set; }
        public string xcblInterConsigneeState { get; set; }
        public string xcblInterConsigneePostalCode { get; set; }
        public string xcblInterConsigneeCountryCode { get; set; }
        public string xcblInterConsigneeContactName { get; set; }
        public string xcblInterConsigneeContactNumber { get; set; }
        public string xcblInterConsigneeAltContName { get; set; }
        public string xcblInterConsigneeAltContNumber { get; set; }
        public string xcblShipFromName { get; set; }
        public Nullable<long> xcblShipFromNameID { get; set; }
        public string xcblShipFromAddress1 { get; set; }
        public string xcblShipFromAddress2 { get; set; }
        public string xcblShipFromCity { get; set; }
        public string xcblShipFromState { get; set; }
        public string xcblShipFromPostalCode { get; set; }
        public string xcblShipFromCountryCode { get; set; }
        public string xcblShipFromContactName { get; set; }
        public string xcblShipFromContactNumber { get; set; }
        public string xcblShipFromAltContName { get; set; }
        public string xcblShipFromAltContNumber { get; set; }
        public string xcblBillToName { get; set; }
        public Nullable<long> xcblBillToNameID { get; set; }
        public string xcblBillToAddress1 { get; set; }
        public string xcblBillToAddress2 { get; set; }
        public string xcblBillToCity { get; set; }
        public string xcblBillToState { get; set; }
        public string xcblBillToPostalCode { get; set; }
        public string xcblBillToCountryCode { get; set; }
        public string xcblBillToContactName { get; set; }
        public string xcblBillToContactNumber { get; set; }
        public string xcblBillToAltContName { get; set; }
        public string xcblBillToAltContNumber { get; set; }
        public string xcblConsigneeStreetAddress3 { get; set; }
        public string xcblConsigneeStreetAddress4 { get; set; }
        public string xcblInterConsigneeStreetAddress3 { get; set; }
        public string xcblInterConsigneeStreetAddress4 { get; set; }
        public string xcblBillToStreetAddress3 { get; set; }
        public string xcblBillToStreetAddress4 { get; set; }
        public string xcblShipFromStreetAddress3 { get; set; }
        public string xcblShipFromStreetAddress4 { get; set; }
        public Nullable<System.DateTime> xcblOrderedDate { get; set; }
        public string xcblTextData { get; set; }
        public bool isxcblAcceptanceRequired { get; set; }
        public bool isxcblProcessed { get; set; }
        public bool isxcblRejected { get; set; }
        public Nullable<System.DateTime> xcblProcessingDate { get; set; }
        public string xcblUDF01 { get; set; }
        public string xcblUDF02 { get; set; }
        public string xcblUDF03 { get; set; }
        public string xcblUDF04 { get; set; }
        public string xcblUDF05 { get; set; }
        public string xcblUDF06 { get; set; }
        public string xcblUDF07 { get; set; }
        public string xcblUDF08 { get; set; }
        public string xcblUDF09 { get; set; }
        public string xcblUDF10 { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XcblSummaryDetail> XcblSummaryDetails { get; set; }
    }
}
