//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCBL_MER000Authentication
    {
        public int ID { get; set; }
        public string WebUsername { get; set; }
        public string WebPassword { get; set; }
        public string WebHashKey { get; set; }
        public string FtpUsername { get; set; }
        public string FtpPassword { get; set; }
        public string FtpServerInFolderPath { get; set; }
        public string FtpServerOutFolderPath { get; set; }
        public string LocalFilePath { get; set; }
        public string WebContactName { get; set; }
        public string WebContactCompany { get; set; }
        public string WebContactEmail { get; set; }
        public string WebContactPhone1 { get; set; }
        public string WebContactPhone2 { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
