//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class XcblSummaryDetail
    {
        public long xcblDetailID { get; set; }
        public Nullable<long> xcblHeaderID { get; set; }
        public string xcblTradingPartner { get; set; }
        public string xcblBOLNo { get; set; }
        public string xcblManifestNo { get; set; }
        public string xcblCommodityType { get; set; }
        public string xcblCommodityDescription { get; set; }
        public string xcblUnitOfMeasure { get; set; }
        public Nullable<decimal> xcblWeight { get; set; }
        public Nullable<long> xcblQuantity { get; set; }
        public Nullable<decimal> xcblCubicFeet { get; set; }
        public string xcblUDF01 { get; set; }
        public string xcblUDF02 { get; set; }
        public string xcblUDF03 { get; set; }
        public string xcblUDF04 { get; set; }
        public string xcblUDF05 { get; set; }
        public string xcblUDF06 { get; set; }
        public string xcblUDF07 { get; set; }
        public string xcblUDF08 { get; set; }
        public string xcblUDF09 { get; set; }
        public string xcblUDF10 { get; set; }
        public string ProFlags01 { get; set; }
        public string ProFlags02 { get; set; }
        public string ProFlags03 { get; set; }
        public string ProFlags04 { get; set; }
        public string ProFlags05 { get; set; }
        public string ProFlags06 { get; set; }
        public string ProFlags07 { get; set; }
        public string ProFlags08 { get; set; }
        public string ProFlags09 { get; set; }
        public string ProFlags10 { get; set; }
        public string ProFlags11 { get; set; }
        public string ProFlags12 { get; set; }
        public string ProFlags13 { get; set; }
        public string ProFlags14 { get; set; }
        public string ProFlags15 { get; set; }
        public string ProFlags16 { get; set; }
        public string ProFlags17 { get; set; }
        public string ProFlags18 { get; set; }
        public string ProFlags19 { get; set; }
        public string ProFlags20 { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual XcblSummaryHeader XcblSummaryHeader { get; set; }
    }
}
