//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.Web.Tests.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M4PL.Web.Tests.ResourceFile.JobDetails", typeof(JobDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT_837.
        /// </summary>
        internal static string AttributeCode {
            get {
                return ResourceManager.GetString("AttributeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string AttributeQty {
            get {
                return ResourceManager.GetString("AttributeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTW893.
        /// </summary>
        internal static string CodeGtw {
            get {
                return ResourceManager.GetString("CodeGtw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS0730.
        /// </summary>
        internal static string ConsigneeCode {
            get {
                return ResourceManager.GetString("ConsigneeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cso-.
        /// </summary>
        internal static string CSOSearch {
            get {
                return ResourceManager.GetString("CSOSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSO-2378JKD.
        /// </summary>
        internal static string CustomerPurchaseOrder {
            get {
                return ResourceManager.GetString("CustomerPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSO-0HRD7-NDF78.
        /// </summary>
        internal static string CustomerSalesOrder {
            get {
                return ResourceManager.GetString("CustomerSalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC-PD936.
        /// </summary>
        internal static string DocCode {
            get {
                return ResourceManager.GetString("DocCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUM-DC846.
        /// </summary>
        internal static string NumberCode {
            get {
                return ResourceManager.GetString("NumberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL-27.
        /// </summary>
        internal static string PlantCode {
            get {
                return ResourceManager.GetString("PlantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string TypeGtw {
            get {
                return ResourceManager.GetString("TypeGtw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UD 937J.
        /// </summary>
        internal static string UD2 {
            get {
                return ResourceManager.GetString("UD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JFR8934.
        /// </summary>
        internal static string UD5 {
            get {
                return ResourceManager.GetString("UD5", resourceCulture);
            }
        }
    }
}
