//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4PL.Web.Tests.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M4PL.Web.Tests.ResourceFile.ProgramDetails", typeof(ProgramDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC.
        /// </summary>
        internal static string ApptCode {
            get {
                return ResourceManager.GetString("ApptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATR-01.
        /// </summary>
        internal static string AttCode {
            get {
                return ResourceManager.GetString("AttCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string AttQty {
            get {
                return ResourceManager.GetString("AttQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJ-CD-01.
        /// </summary>
        internal static string CJCode {
            get {
                return ResourceManager.GetString("CJCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Details.
        /// </summary>
        internal static string CJTitle {
            get {
                return ResourceManager.GetString("CJTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHS-CD-01.
        /// </summary>
        internal static string PhaseCode {
            get {
                return ResourceManager.GetString("PhaseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRG-GTW-01.
        /// </summary>
        internal static string PrgGtwCode {
            get {
                return ResourceManager.GetString("PrgGtwCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string PrgGtwDuration {
            get {
                return ResourceManager.GetString("PrgGtwDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRG-GTW.
        /// </summary>
        internal static string PrgGtwTitle {
            get {
                return ResourceManager.GetString("PrgGtwTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRG-01.
        /// </summary>
        internal static string ProgramCode {
            get {
                return ResourceManager.GetString("ProgramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJ-CD-01.
        /// </summary>
        internal static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AX.
        /// </summary>
        internal static string ReasonCode {
            get {
                return ResourceManager.GetString("ReasonCode", resourceCulture);
            }
        }
    }
}
