
 
 IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRGRM043ProgramCostLocations' AND COLUMN_NAME = 'StatusId')
			 BEGIN 
					ALTER TABLE PRGRM043ProgramCostLocations
					ADD StatusId int NOT NULL DEFAULT(1) 
			 END
		ELSE
			 BEGIN
			   PRINT 1
			 END
IF NOT EXISTS( SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PRGRM042ProgramBillableLocations' AND COLUMN_NAME = 'StatusId')
			 BEGIN 
				ALTER TABLE PRGRM042ProgramBillableLocations
				ADD StatusId int NOT NULL DEFAULT(1)
			 END
	ELSE
			 BEGIN
				 PRINT 2
			 END
