CREATE NONCLUSTERED INDEX ix_JOBDL020GatewaysOnJobIDIndexAft ON JOBDL020Gateways ([JobID]);
CREATE NONCLUSTERED INDEX ix_JOBDL020GatewaysOnGwyDDPNewIndexAft ON JOBDL020Gateways ([GwyDDPNew]);
CREATE NONCLUSTERED INDEX ix_JOBDL020GatewaysOnGwyOrderTypeIndexAft ON JOBDL020Gateways ([GwyOrderType]); 