DELETE FROM SYSTM000ColumnsAlias where ColTableName='CustContact'

INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConCodeId', N'Code', N'Code', NULL, NULL, N'', 4, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ContactMSTRID', N'Contact', N'Contact', NULL, NULL, NULL, 6, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConTitle', N'Title', N'Title', NULL, NULL, N'', 5, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConPrimaryRecordId', N'Customer', N'Customer', NULL, NULL, N'', 2, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConItemNumber', N'Item', N'Item', NULL, NULL, N'', 3, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'DateChanged', N'Changed On', N'Changed On', NULL, NULL, N'', 11, 1, 0, 1, 1, N'MM/dd/yyyy hh:mm tt', 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'DateEntered', N'Entered On', N'Entered On', NULL, NULL, NULL, 9, 1, 0, 1, 1, N'MM/dd/yyyy hh:mm tt', 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ChangedBy', N'Changed By', N'Changed By', NULL, NULL, N'', 10, 1, 0, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'EnteredBy', N'Entered By', N'Entered By', NULL, NULL, N'', 8, 1, 0, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'Id', N'ID', N'ID', NULL, NULL, N'', 1, 1, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'StatusId', N'Status', N'Status', 39, N'Status', N'', 7, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConJobTitle', N'Job Title', N'Job Title', NULL, NULL, NULL, 12, 1, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConEmailAddress', N'Primary Email', N'Primary Email', NULL, NULL, NULL, 13, 1, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConMobilePhone', N'Mobile Phone', N'Mobile Phone', NULL, NULL, NULL, 14, 1, 1, 1, 1, NULL, 0, 0, N'999-000-0000')
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConBusinessPhone', N'Business Phone', N'Business Phone', NULL, NULL, NULL, 15, 1, 1, 1, 1, NULL, 0, 0, N'999-000-0000')
INSERT [dbo].[SYSTM000ColumnsAlias] ([LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (N'EN', N'CustContact', N'ConBusinessFullAddress', N'Bussiness Adress', N'Bussiness Adress', NULL, NULL, NULL, 16, 1, 1, 1, 1, NULL, 0, 0, NULL)



