
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=1, ColIsVisible=1, isgridcolumn =1  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'Id'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=2, ColIsVisible=0, isgridcolumn =0   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'JobID'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=3, ColIsVisible=0, isgridcolumn =0   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'JobID'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=4, ColIsVisible=0, isgridcolumn =0   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'ProgramID'


UPDATE SYSTM000ColumnsAlias SET ColSortOrder=5, ColIsVisible=1 , isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayACD'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=6, ColIsVisible=1 , isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyCompleted'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=7, ColIsVisible=1 , isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewaySortOrder'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=8, ColIsVisible=1 , isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayCode'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=9, ColIsVisible=1 , isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayTitle'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=10, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayDuration'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=11, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GatewayUnitId'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=12, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayPCD'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=13, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyAttachments'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=14, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyDateRefTypeId'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=15, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'StatusId'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=16, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'Scanner'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=17, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyShipStatusReasonCode'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=18, ColIsVisible=1, isgridcolumn =1   WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyShipApptmtReasonCode'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=19, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyOrderType'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=20, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyShipmentType'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=21, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyUpdatedById'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=22, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyClosedOn'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=23, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyClosedBy'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=24, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayECD'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=25, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayAnalyst'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=26, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayResponsible'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=27, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyPerson'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=28, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyPhone'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=29, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyEmail'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=29, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyTitle'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=30, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyDDPCurrent'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=31, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyDDPNew'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=32, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyUprWindow'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=33, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyLwrWindow'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=34, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyUprDate'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=35, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyLwrDate'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=36, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'CancelOrder'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=37, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'DateCancelled'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=38, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'DateComment'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=39, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'DateEmail'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=40, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'StatusCode'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=41, ColIsVisible=0, isgridcolumn =0  WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GatewayTypeId'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=42, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayDescription'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=43, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyGatewayDefault'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=44, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyComment'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=45, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'GwyProcessingFlags'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=46, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'DateEntered'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=47, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'EnteredBy'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=48, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'DateChanged'
UPDATE SYSTM000ColumnsAlias SET ColSortOrder=49, ColIsVisible=0, isgridcolumn =0 WHERE COLTABLENAME='JOBGATEWAY' AND COLCOLUMNNAME= 'ChangedBy'



update SYSTM000ColumnSettingsByUser set
ColSortOrder = 'Id,JobID,ProgramID,GwyGatewayACD,GwyCompleted,GwyGatewaySortOrder,GwyGatewayCode,GwyGatewayTitle,GwyGatewayDuration,GatewayUnitId,GwyGatewayPCD,GwyAttachments,GwyDateRefTypeId,StatusId,Scanner,GwyShipStatusReasonCode,GwyShipApptmtReasonCode,GwyOrderType,GwyShipmentType,GwyUpdatedById,GwyClosedOn,GwyClosedBy,GwyGatewayECD,GwyGatewayAnalyst,GwyGatewayResponsible,GwyPerson,GwyPhone,GwyEmail,GwyTitle,GwyDDPCurrent,GwyDDPNew,GwyUprWindow,GwyLwrWindow,GwyUprDate,GwyLwrDate,CancelOrder,DateCancelled,DateComment,DateEmail,StatusCode,GatewayTypeId,GwyGatewayDescription,GwyGatewayDefault,GwyComment,GwyProcessingFlags,DateEntered,EnteredBy,DateChanged,ChangedBy'
,ColNotVisible='JobID,ProgramID,GwyOrderType,GwyShipmentType,GwyUpdatedById,GwyClosedOn,GwyClosedBy,GwyGatewayECD,GwyGatewayAnalyst,GwyGatewayResponsible,GwyPerson,GwyPhone,GwyEmail,GwyTitle,GwyDDPCurrent,GwyDDPNew,GwyUprWindow,GwyLwrWindow,GwyUprDate,GwyLwrDate,CancelOrder,DateCancelled,DateComment,DateEmail,StatusCode,GatewayTypeId,GwyGatewayDescription,GwyGatewayDefault,GwyComment,GwyProcessingFlags,DateEntered,EnteredBy,DateChanged,ChangedBy'
WHERE ColTableName='JOBGATEWAY' 

