INSERT INTO [dbo].[JOBDL030Attributes]
           ([JobID]
           ,[AjbLineOrder]
           ,[AjbAttributeCode]
           ,[AjbAttributeTitle]
           ,[AjbAttributeDescription]
           ,[AjbAttributeComments]
           ,[AjbAttributeQty]
           ,[AjbUnitTypeId]
           ,[AjbDefault]
           ,[StatusId]
           ,[ProFlags01]
           ,[ProFlags02]
           ,[ProFlags03]
           ,[ProFlags04]
           ,[ProFlags05]
           ,[ProFlags06]
           ,[ProFlags07]
           ,[ProFlags08]
           ,[ProFlags09]
           ,[ProFlags10]
           ,[ProFlags11]
           ,[ProFlags12]
           ,[ProFlags13]
           ,[ProFlags14]
           ,[ProFlags15]
           ,[ProFlags16]
           ,[ProFlags17]
           ,[ProFlags18]
           ,[ProFlags19]
           ,[ProFlags20]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT
            JA.[JobID]
           ,JA.[AjbLineOrder]
           ,JA.[AjbAttributeCode]
           ,JA.[AjbAttributeTitle]
           ,JA.[AjbAttributeDescription]
           ,JA.[AjbAttributeComments]
           ,JA.[AjbAttributeQty]
           ,JA.[AjbUnitTypeId]
           ,JA.[AjbDefault]
           ,JA.[StatusId]
           ,JA.[ProFlags01]
           ,JA.[ProFlags02]
           ,JA.[ProFlags03]
           ,JA.[ProFlags04]
           ,JA.[ProFlags05]
           ,JA.[ProFlags06]
           ,JA.[ProFlags07]
           ,JA.[ProFlags08]
           ,JA.[ProFlags09]
           ,JA.[ProFlags10]
           ,JA.[ProFlags11]
           ,JA.[ProFlags12]
           ,JA.[ProFlags13]
           ,JA.[ProFlags14]
           ,JA.[ProFlags15]
           ,JA.[ProFlags16]
           ,JA.[ProFlags17]
           ,JA.[ProFlags18]
           ,JA.[ProFlags19]
           ,JA.[ProFlags20]
           ,JA.[DateEntered]
           ,JA.[EnteredBy]
           ,JA.[DateChanged]
           ,JA.[ChangedBy] FROM [M4PL_3030_Test].[dbo].[JOBDL030Attributes] JA
		   LEFT JOIN [M4PL_3030_Test].[dbo].[JOBDL000Master] J ON J.Id=JA.JobID
		   LEFT JOIN [M4PL_3030_Test].[dbo].[PRGRM000Master] p on p.Id = j.ProgramID
		   where p.PrgOrgID = 1
GO


