INSERT INTO [dbo].[JOBDL060Ref_CostSheetJob]
           ([JobID]
           ,[CstLineItem]
           ,[CstChargeID]
           ,[CstChargeCode]
           ,[CstTitle]
           ,[CstSurchargeOrder]
           ,[CstSurchargePercent]
           ,[ChargeTypeId]
           ,[CstNumberUsed]
           ,[CstDuration]
           ,[CstQuantity]
           ,[CostUnitId]
           ,[CstCostRate]
           ,[CstCost]
           ,[CstMarkupPercent]
           ,[CstRevenueRate]
           ,[CstRevDuration]
           ,[CstRevQuantity]
           ,[CstRevBillable]
           ,[CstComments]
           ,[StatusId]
           ,[EnteredBy]
           ,[DateEntered]
           ,[ChangedBy]
           ,[DateChanged])
     SELECT
            J.[Id]
           ,JRC.[CstLineItem]
           ,JRC.[CstChargeID]
           ,JRC.[CstChargeCode]
           ,JRC.[CstTitle]
           ,JRC.[CstSurchargeOrder]
           ,JRC.[CstSurchargePercent]
           ,JRC.[ChargeTypeId]
           ,JRC.[CstNumberUsed]
           ,JRC.[CstDuration]
           ,JRC.[CstQuantity]
           ,JRC.[CostUnitId]
           ,JRC.[CstCostRate]
           ,JRC.[CstCost]
           ,JRC.[CstMarkupPercent]
           ,JRC.[CstRevenueRate]
           ,JRC.[CstRevDuration]
           ,JRC.[CstRevQuantity]
           ,JRC.[CstRevBillable]
           ,JRC.[CstComments]
           ,JRC.[StatusId]
           ,JRC.[EnteredBy]
           ,JRC.[DateEntered]
           ,JRC.[ChangedBy]
           ,JRC.[DateChanged] FROM [M4PL_3030_Test].[dbo].[JOBDL060Ref_CostSheetJob] JRC
		   INNER JOIN [dbo].[JOBDL000Master] J ON J.[3030Id] = JRC.JobID
		   INNER JOIN [dbo].[PRGRM000Master] P ON P.[Id] = J.ProgramID
		   WHERE P.PrgOrgID = 1
GO


