

DELETE FROM SYSTM000ColumnsAlias where ColTableName='OrgPocContact'

INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (515, N'EN', N'OrgPocContact', N'Id', N'ID', N'ID', NULL, NULL, N'', 1, 1, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (516, N'EN', N'OrgPocContact', N'ConOrgId', N'Org ID', N'Org ID', NULL, NULL, N'', 2, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (517, N'EN', N'OrgPocContact', N'ContactMSTRID', N'Contact', N'Contact', NULL, NULL, NULL, 3, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (518, N'EN', N'OrgPocContact', N'ConItemNumber', N'Item', N'Item', NULL, NULL, NULL, 4, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (519, N'EN', N'OrgPocContact', N'ConCodeId', N'Code', N'Code', NULL, NULL, NULL, 5, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (520, N'EN', N'OrgPocContact', N'ConTitle', N'Title', N'Title', NULL, NULL, NULL, 6, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (521, N'EN', N'OrgPocContact', N'ConTableTypeId', N'Type', N'Type', 31, N'PocType', NULL, 7, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (522, N'EN', N'OrgPocContact', N'ConDescription', N'Description', N'Description', NULL, NULL, NULL, 8, 0, 0, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (523, N'EN', N'OrgPocContact', N'ConInstruction', N'Instructions', N'Instructions', NULL, NULL, NULL, 9, 0, 0, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (524, N'EN', N'OrgPocContact', N'ConIsDefault', N'Default', N'Default', NULL, NULL, NULL, 10, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (525, N'EN', N'OrgPocContact', N'StatusId', N'Status', N'Status', 39, N'Status', N'', 11, 0, 1, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (526, N'EN', N'OrgPocContact', N'DateEntered', N'Entered On', N'Entered On', NULL, NULL, N'', 12, 1, 0, 1, 1, N'MM/dd/yyyy hh:mm tt', 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (527, N'EN', N'OrgPocContact', N'EnteredBy', N'Entered By', N'Entered By', NULL, NULL, N'', 13, 1, 0, 1, 1, NULL, 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (528, N'EN', N'OrgPocContact', N'DateChanged', N'Changed On', N'Changed On', NULL, NULL, N'', 14, 1, 0, 1, 1, N'MM/dd/yyyy hh:mm tt', 0, 0, NULL)
INSERT [dbo].[SYSTM000ColumnsAlias] ([Id], [LangCode], [ColTableName], [ColColumnName], [ColAliasName], [ColCaption], [ColLookupId], [ColLookupCode], [ColDescription], [ColSortOrder], [ColIsReadOnly], [ColIsVisible], [ColIsDefault], [StatusId], [ColDisplayFormat], [ColAllowNegativeValue], [ColIsGroupBy], [ColMask]) VALUES (529, N'EN', N'OrgPocContact', N'ChangedBy', N'Changed By', N'Changed By', NULL, NULL, N'', 15, 1, 0, 1, 1, NULL, 0, 0, NULL)  