INSERT INTO [dbo].[PRGRM000Master]
           ([PrgOrgID]
           ,[PrgCustID]
           ,[PrgItemNumber]
           ,[PrgProgramCode]
           ,[PrgProjectCode]
           ,[PrgPhaseCode]
           ,[PrgProgramTitle]
           ,[PrgAccountCode]
           ,[DelEarliest]
           ,[DelLatest]
           ,[DelDay]
           ,[PckEarliest]
           ,[PckLatest]
           ,[PckDay]
           ,[StatusId]
           ,[PrgDateStart]
           ,[PrgDateEnd]
           ,[PrgDeliveryTimeDefault]
           ,[PrgPickUpTimeDefault]
           ,[PrgDescription]
           ,[PrgNotes]
           ,[PrgHierarchyID]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     
           SELECT 1
           ,(SELECT TOP 1 PR.ID FROM [dbo].[CUST000Master] PR WHERE PR.CustCode = (SELECT TOP 1 CustCode FROM [M4PL_3030_Test].[dbo].[CUST000Master] WHERE Id=TS.PrgCustID))
           ,[PrgItemNumber]
           ,[PrgProgramCode]
           ,[PrgProjectCode]
           ,[PrgPhaseCode]
           ,[PrgProgramTitle]
           ,[PrgAccountCode]
           ,[DelEarliest]
           ,[DelLatest]
           ,[DelDay]
           ,[PckEarliest]
           ,[PckLatest]
           ,[PckDay]
           ,[StatusId]
           ,[PrgDateStart]
           ,[PrgDateEnd]
           ,[PrgDeliveryTimeDefault]
           ,[PrgPickUpTimeDefault]
           ,[PrgDescription]
           ,[PrgNotes]
           ,[PrgHierarchyID]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy] FROM [M4PL_3030_Test].[dbo].[PRGRM000Master] TS
		   WHERE TS.PrgOrgID = 1
GO


