INSERT INTO [dbo].[PRGRM040ProgramBillableRate]
           ([PbrPrgrmID]
           ,[PbrCode]
           ,[PbrCustomerCode]
           ,[PbrEffectiveDate]
           ,[PbrTitle]
           ,[RateCategoryTypeId]
           ,[RateTypeId]
           ,[PbrBillablePrice]
           ,[RateUnitTypeId]
           ,[PbrFormat]
           ,[PbrDescription]
           ,[PbrExpression01]
           ,[PbrLogic01]
           ,[PbrExpression02]
           ,[PbrLogic02]
           ,[PbrExpression03]
           ,[PbrLogic03]
           ,[PbrExpression04]
           ,[PbrLogic04]
           ,[PbrExpression05]
           ,[PbrLogic05]
           ,[StatusId]
           ,[PbrVendLocationID]
           ,[EnteredBy]
           ,[DateEntered]
           ,[ChangedBy]
           ,[DateChanged])
     SELECT PF.[Id]
           ,TS.[PbrCode]
           ,TS.[PbrCustomerCode]
           ,TS.[PbrEffectiveDate]
           ,TS.[PbrTitle]
           ,TS.[RateCategoryTypeId]
           ,TS.[RateTypeId]
           ,TS.[PbrBillablePrice]
           ,TS.[RateUnitTypeId]
           ,TS.[PbrFormat]
           ,TS.[PbrDescription]
           ,TS.[PbrExpression01]
           ,TS.[PbrLogic01]
           ,TS.[PbrExpression02]
           ,TS.[PbrLogic02]
           ,TS.[PbrExpression03]
           ,TS.[PbrLogic03]
           ,TS.[PbrExpression04]
           ,TS.[PbrLogic04]
           ,TS.[PbrExpression05]
           ,TS.[PbrLogic05]
           ,TS.[StatusId]
           ,TS.[PbrVendLocationID]
           ,TS.[EnteredBy]
           ,TS.[DateEntered]
           ,TS.[ChangedBy]
           ,TS.[DateChanged] 
		   FROM [M4PL_3030_Test].[dbo].[PRGRM040ProgramBillableRate]  TS
		   INNER join [M4PL_3030_Test].[dbo].[PRGRM000Master] PM on TS.PbrPrgrmID = PM.Id
		   INNER JOIN [dbo].[PRGRM000Master] PF ON PF.PrgProgramCode = PM.PrgProgramCode
		   where PM.PrgOrgID = 1