INSERT INTO [dbo].[PRGRM041ProgramCostRate]
           ([PcrPrgrmID]
           ,[PcrCode]
           ,[PcrVendorCode]
           ,[PcrEffectiveDate]
           ,[PcrTitle]
           ,[RateCategoryTypeId]
           ,[RateTypeId]
           ,[PcrCostRate]
           ,[RateUnitTypeId]
           ,[PcrFormat]
           ,[PcrDescription]
           ,[PcrExpression01]
           ,[PcrLogic01]
           ,[PcrExpression02]
           ,[PcrLogic02]
           ,[PcrExpression03]
           ,[PcrLogic03]
           ,[PcrExpression04]
           ,[PcrLogic04]
           ,[PcrExpression05]
           ,[PcrLogic05]
           ,[StatusId]
           ,[PcrCustomerID]
           ,[EnteredBy]
           ,[DateEntered]
           ,[ChangedBy]
           ,[DateChanged])
	SELECT PF.[Id]
           ,TS.[PcrCode]
           ,TS.[PcrVendorCode]
           ,TS.[PcrEffectiveDate]
           ,TS.[PcrTitle]
           ,TS.[RateCategoryTypeId]
           ,TS.[RateTypeId]
           ,TS.[PcrCostRate]
           ,TS.[RateUnitTypeId]
           ,TS.[PcrFormat]
           ,TS.[PcrDescription]
           ,TS.[PcrExpression01]
           ,TS.[PcrLogic01]
           ,TS.[PcrExpression02]
           ,TS.[PcrLogic02]
           ,TS.[PcrExpression03]
           ,TS.[PcrLogic03]
           ,TS.[PcrExpression04]
           ,TS.[PcrLogic04]
           ,TS.[PcrExpression05]
           ,TS.[PcrLogic05]
           ,TS.[StatusId]
           ,TS.[PcrCustomerID]
           ,TS.[EnteredBy]
           ,TS.[DateEntered]
           ,TS.[ChangedBy]
           ,TS.[DateChanged]
		FROM [M4PL_3030_Test].[dbo].[PRGRM041ProgramCostRate] TS
		   INNER join [M4PL_3030_Test].[dbo].[PRGRM000Master] PM on TS.PcrPrgrmID = PM.Id
		   INNER JOIN [dbo].[PRGRM000Master] PF ON PF.PrgProgramCode = PM.PrgProgramCode
		   where PM.PrgOrgID = 1