INSERT INTO [dbo].[PRGRM070EdiHeader]
           ([PehProgramID]
           ,[PehItemNumber]
           ,[PehEdiCode]
           ,[PehEdiTitle]
           ,[PehEdiDescription]
           ,[PehTradingPartner]
           ,[PehEdiDocument]
           ,[PehEdiVersion]
           ,[PehSCACCode]
           ,[PehSndRcv]
           ,[PehInsertCode]
           ,[PehUpdateCode]
           ,[PehCancelCode]
           ,[PehHoldCode]
           ,[PehOriginalCode]
           ,[PehReturnCode]
           ,[PehInOutFolder]
           ,[PehArchiveFolder]
           ,[PehProcessFolder]
           ,[UDF01]
           ,[UDF02]
           ,[UDF03]
           ,[UDF04]
           ,[UDF05]
           ,[UDF06]
           ,[UDF07]
           ,[UDF08]
           ,[UDF09]
           ,[UDF10]
           ,[PehAttachments]
           ,[StatusId]
           ,[PehDateStart]
           ,[PehDateEnd]
           ,[EnteredBy]
           ,[DateEntered]
           ,[ChangedBy]
           ,[DateChanged]
		   ,[3030Id])
     
     SELECT PM.Id
           ,TS.[PehItemNumber]
           ,TS.[PehEdiCode]
           ,TS.[PehEdiTitle]
           ,TS.[PehEdiDescription]
           ,TS.[PehTradingPartner]
           ,TS.[PehEdiDocument]
           ,TS.[PehEdiVersion]
           ,TS.[PehSCACCode]
           ,TS.[PehSndRcv]
           ,TS.[PehInsertCode]
           ,TS.[PehUpdateCode]
           ,TS.[PehCancelCode]
           ,TS.[PehHoldCode]
           ,TS.[PehOriginalCode]
           ,TS.[PehReturnCode]
           ,TS.[PehInOutFolder]
           ,TS.[PehArchiveFolder]
           ,TS.[PehProcessFolder]
           ,TS.[UDF01]
           ,TS.[UDF02]
           ,TS.[UDF03]
           ,TS.[UDF04]
           ,TS.[UDF05]
           ,TS.[UDF06]
           ,TS.[UDF07]
           ,TS.[UDF08]
           ,TS.[UDF09]
           ,TS.[UDF10]
           ,TS.[PehAttachments]
           ,TS.[StatusId]
           ,TS.[PehDateStart]
           ,TS.[PehDateEnd]
           ,TS.[EnteredBy]
           ,TS.[DateEntered]
           ,TS.[ChangedBy]
           ,TS.[DateChanged]
		   ,TS.Id FROM [M4PL_3030_Test].[dbo].[PRGRM070EdiHeader] TS
		   INNER join [dbo].[PRGRM000Master] PM on TS.PehProgramID = PM.[3030Id]
		   where PM.PrgOrgID = 1
GO


