INSERT INTO [dbo].[PRGRM020Ref_AttributesDefault]
           ([ProgramID]
           ,[AttItemNumber]
           ,[AttCode]
           ,[AttTitle]
           ,[AttDescription]
           ,[AttComments]
           ,[AttQuantity]
           ,[UnitTypeId]
           ,[AttDefault]
           ,[StatusId]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT PM.[Id]
           ,TS.[AttItemNumber]
           ,TS.[AttCode]
           ,TS.[AttTitle]
           ,TS.[AttDescription]
           ,TS.[AttComments]
           ,TS.[AttQuantity]
           ,TS.[UnitTypeId]
           ,TS.[AttDefault]
           ,TS.[StatusId]
           ,TS.[DateEntered]
           ,TS.[EnteredBy]
           ,TS.[DateChanged]
           ,TS.[ChangedBy]
	FROM [M4PL_3030_Test].[dbo].[PRGRM020Ref_AttributesDefault] TS
		   INNER join [dbo].[PRGRM000Master] PM on TS.ProgramID = PM.[3030Id]
		   where PM.PrgOrgID = 1