INSERT INTO [dbo].[PRGRM030ShipStatusReasonCodes]
           ([PscOrgID]
           ,[PscProgramID]
           ,[PscShipItem]
           ,[PscShipReasonCode]
           ,[PscShipLength]
           ,[PscShipInternalCode]
           ,[PscShipPriorityCode]
           ,[PscShipTitle]
           ,[PscShipDescription]
           ,[PscShipComment]
           ,[PscShipCategoryCode]
           ,[PscShipUser01Code]
           ,[PscShipUser02Code]
           ,[PscShipUser03Code]
           ,[PscShipUser04Code]
           ,[PscShipUser05Code]
           ,[StatusId]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT TS.[PscOrgID]
           ,PF.[Id]
           ,TS.[PscShipItem]
           ,TS.[PscShipReasonCode]
           ,TS.[PscShipLength]
           ,TS.[PscShipInternalCode]
           ,TS.[PscShipPriorityCode]
           ,TS.[PscShipTitle]
           ,TS.[PscShipDescription]
           ,TS.[PscShipComment]
           ,TS.[PscShipCategoryCode]
           ,TS.[PscShipUser01Code]
           ,TS.[PscShipUser02Code]
           ,TS.[PscShipUser03Code]
           ,TS.[PscShipUser04Code]
           ,TS.[PscShipUser05Code]
           ,PSR.Id--TS.[StatusId]
           ,TS.[DateEntered]
           ,TS.[EnteredBy]
           ,TS.[DateChanged]
           ,TS.[ChangedBy]
	FROM [M4PL_3030_Test].[dbo].[PRGRM030ShipStatusReasonCodes] TS
		   INNER join [M4PL_3030_Test].[dbo].[PRGRM000Master] PM on TS.PscProgramID = PM.Id
		   INNER JOIN [dbo].[PRGRM000Master] PF ON PF.PrgProgramCode = PM.PrgProgramCode
		   LEFT JOIN [M4PL_3030_Test].[dbo].[SYSTM000Ref_Options] RPS ON TS.StatusId = RPS.Id
		   LEFT JOIN [dbo].[SYSTM000Ref_Options] PSR ON PSR.SysLookupId = RPS.SysLookupId AND PSR.SysLookupCode = RPS.SysLookupCode AND PSR.SysOptionName = RPS.SysOptionName
		   where PM.PrgOrgID = 1