INSERT INTO [dbo].[PRGRM030ShipStatusReasonCodes]
           ([PscOrgID]
           ,[PscProgramID]
           ,[PscShipItem]
           ,[PscShipReasonCode]
           ,[PscShipLength]
           ,[PscShipInternalCode]
           ,[PscShipPriorityCode]
           ,[PscShipTitle]
           ,[PscShipDescription]
           ,[PscShipComment]
           ,[PscShipCategoryCode]
           ,[PscShipUser01Code]
           ,[PscShipUser02Code]
           ,[PscShipUser03Code]
           ,[PscShipUser04Code]
           ,[PscShipUser05Code]
           ,[StatusId]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT TS.[PscOrgID]
           ,PM.[Id]
           ,TS.[PscShipItem]
           ,TS.[PscShipReasonCode]
           ,TS.[PscShipLength]
           ,TS.[PscShipInternalCode]
           ,TS.[PscShipPriorityCode]
           ,TS.[PscShipTitle]
           ,TS.[PscShipDescription]
           ,TS.[PscShipComment]
           ,TS.[PscShipCategoryCode]
           ,TS.[PscShipUser01Code]
           ,TS.[PscShipUser02Code]
           ,TS.[PscShipUser03Code]
           ,TS.[PscShipUser04Code]
           ,TS.[PscShipUser05Code]
           ,TS.[StatusId]
           ,TS.[DateEntered]
           ,TS.[EnteredBy]
           ,TS.[DateChanged]
           ,TS.[ChangedBy]
	FROM [M4PL_3030_Test].[dbo].[PRGRM030ShipStatusReasonCodes] TS
		   INNER join [dbo].[PRGRM000Master] PM on TS.PscProgramID = PM.[3030Id]
		   where PM.PrgOrgID = 1