INSERT INTO [dbo].[PRGRM031ShipApptmtReasonCodes]
           ([PacOrgID]
           ,[PacProgramID]
           ,[PacApptItem]
           ,[PacApptReasonCode]
           ,[PacApptLength]
           ,[PacApptInternalCode]
           ,[PacApptPriorityCode]
           ,[PacApptTitle]
           ,[PacApptDescription]
           ,[PacApptComment]
           ,[PacApptCategoryCodeId]
           ,[PacApptUser01Code]
           ,[PacApptUser02Code]
           ,[PacApptUser03Code]
           ,[PacApptUser04Code]
           ,[PacApptUser05Code]
           ,[StatusId]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT [PacOrgID]
           ,PM.[Id]
           ,TS.[PacApptItem]
           ,TS.[PacApptReasonCode]
           ,TS.[PacApptLength]
           ,TS.[PacApptInternalCode]
           ,TS.[PacApptPriorityCode]
           ,TS.[PacApptTitle]
           ,TS.[PacApptDescription]
           ,TS.[PacApptComment]
           ,ISNULL((select Id from SYSTM000Ref_Options where SysLookupCode='PacApptCategoryCode' AND SysOptionName=TS.[PacApptCategoryCode]),1285)
           ,TS.[PacApptUser01Code]
           ,TS.[PacApptUser02Code]
           ,TS.[PacApptUser03Code]
           ,TS.[PacApptUser04Code]
           ,TS.[PacApptUser05Code]
           ,TS.[StatusId]
           ,TS.[DateEntered]
           ,TS.[EnteredBy]
           ,TS.[DateChanged]
           ,TS.[ChangedBy]
		  FROM [M4PL_3030_Test].[dbo].[PRGRM031ShipApptmtReasonCodes] TS
		   INNER join [dbo].[PRGRM000Master] PM on TS.PacProgramID = PM.[3030Id]
		   where PM.PrgOrgID = 1