INSERT INTO [dbo].[PRGRM031ShipApptmtReasonCodes]
           ([PacOrgID]
           ,[PacProgramID]
           ,[PacApptItem]
           ,[PacApptReasonCode]
           ,[PacApptLength]
           ,[PacApptInternalCode]
           ,[PacApptPriorityCode]
           ,[PacApptTitle]
           ,[PacApptDescription]
           ,[PacApptComment]
           ,[PacApptCategoryCode]
           ,[PacApptUser01Code]
           ,[PacApptUser02Code]
           ,[PacApptUser03Code]
           ,[PacApptUser04Code]
           ,[PacApptUser05Code]
           ,[StatusId]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT [PacOrgID]
           ,PF.[Id]
           ,TS.[PacApptItem]
           ,TS.[PacApptReasonCode]
           ,TS.[PacApptLength]
           ,TS.[PacApptInternalCode]
           ,TS.[PacApptPriorityCode]
           ,TS.[PacApptTitle]
           ,TS.[PacApptDescription]
           ,TS.[PacApptComment]
           ,TS.[PacApptCategoryCode]
           ,TS.[PacApptUser01Code]
           ,TS.[PacApptUser02Code]
           ,TS.[PacApptUser03Code]
           ,TS.[PacApptUser04Code]
           ,TS.[PacApptUser05Code]
           ,PSR.Id--TS.[StatusId]
           ,TS.[DateEntered]
           ,TS.[EnteredBy]
           ,TS.[DateChanged]
           ,TS.[ChangedBy]
		  FROM [M4PL_3030_Test].[dbo].[PRGRM031ShipApptmtReasonCodes] TS
		   INNER join [M4PL_3030_Test].[dbo].[PRGRM000Master] PM on TS.PacProgramID = PM.Id
		   INNER JOIN [dbo].[PRGRM000Master] PF ON PF.PrgProgramCode = PM.PrgProgramCode
		   LEFT JOIN [M4PL_3030_Test].[dbo].[SYSTM000Ref_Options] RPS ON TS.StatusId = RPS.Id
		   LEFT JOIN [dbo].[SYSTM000Ref_Options] PSR ON PSR.SysLookupId = RPS.SysLookupId AND PSR.SysLookupCode = RPS.SysLookupCode AND PSR.SysOptionName = RPS.SysOptionName
		   where PM.PrgOrgID = 1