INSERT INTO [dbo].[MVOC010Ref_Questions]
           ([MVOCID]
           ,[QueQuestionNumber]
           ,[QueCode]
           ,[QueTitle]
           ,[QueDescription]
           ,[QuesTypeId]
           ,[StatusId]
           ,[QueType_YNAnswer]
           ,[QueType_YNDefault]
           ,[QueType_RangeLo]
           ,[QueType_RangeHi]
           ,[QueType_RangeAnswer]
           ,[QueType_RangeDefault]
           ,[DateEntered]
           ,[EnteredBy]
           ,[DateChanged]
           ,[ChangedBy])
     SELECT MP.Id
      ,[QueQuestionNumber]
      ,[QueCode]
      ,[QueTitle]
      ,[QueDescription]
      ,[QuesTypeId]
      ,RQ.[StatusId]
      ,[QueType_YNAnswer]
      ,[QueType_YNDefault]
      ,[QueType_RangeLo]
      ,[QueType_RangeHi]
      ,[QueType_RangeAnswer]
      ,[QueType_RangeDefault]
      ,RQ.[DateEntered]
      ,RQ.[EnteredBy]
      ,RQ.[DateChanged]
      ,RQ.[ChangedBy]
  FROM  M4PL_3030_Test.[dbo].[MVOC010Ref_Questions]RQ
  INNER JOIN MVOC000Program MP ON RQ.id=MP.[3030Id]
  WHERE VocOrgID=1