//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBSTesting_ConsoleApp.PBS_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Copyright © Programmed Business Solutions - October 2010", ConfigurationName="PBS_ServiceReference.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="Copyright © Programmed Business Solutions - October 2010/GetSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSQL(string strSQL, string strConnect);
        
        [System.ServiceModel.OperationContractAttribute(Action="Copyright © Programmed Business Solutions - October 2010/GetSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSQLAsync(string strSQL, string strConnect);
        
        [System.ServiceModel.OperationContractAttribute(Action="Copyright © Programmed Business Solutions - October 2010/SQLtoCSV_File", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SQLtoCSV_File(string strSQL, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Copyright © Programmed Business Solutions - October 2010/SQLtoCSV_File", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SQLtoCSV_FileAsync(string strSQL, string User, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PBSTesting_ConsoleApp.PBS_ServiceReference.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PBSTesting_ConsoleApp.PBS_ServiceReference.Service1Soap>, PBSTesting_ConsoleApp.PBS_ServiceReference.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSQL(string strSQL, string strConnect) {
            return base.Channel.GetSQL(strSQL, strConnect);
        }
        
        public System.Threading.Tasks.Task<string> GetSQLAsync(string strSQL, string strConnect) {
            return base.Channel.GetSQLAsync(strSQL, strConnect);
        }
        
        public string SQLtoCSV_File(string strSQL, string User, string Password) {
            return base.Channel.SQLtoCSV_File(strSQL, User, Password);
        }
        
        public System.Threading.Tasks.Task<string> SQLtoCSV_FileAsync(string strSQL, string User, string Password) {
            return base.Channel.SQLtoCSV_FileAsync(strSQL, User, Password);
        }
    }
}
