ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyOrdered int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyExpected int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyOnHand int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyDamaged int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyOnHold int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyShortOver int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoQtyOver int

ALTER TABLE dbo.JOBDL010Cargo
ALTER COLUMN CgoReasonCodeOSD [nvarchar](30)