ALTER TABLE [dbo].[JOBDL000Master]  WITH NOCHECK ADD  CONSTRAINT [FK_JOBDL000Master_JobQtyUnitTypeId_SYSTM000Ref_Options] FOREIGN KEY([JobQtyUnitTypeId])
REFERENCES [dbo].[SYSTM000Ref_Options] ([Id])
GO
ALTER TABLE [dbo].[JOBDL000Master] CHECK CONSTRAINT [FK_JOBDL000Master_JobQtyUnitTypeId_SYSTM000Ref_Options]
GO