UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'Account'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'AppDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'AttItemNumber', [TblParentIdFieldName]=N'AttPrimaryRecordID' WHERE [SysRefName]=N'Attachment'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'ColumnAlias'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'ConDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'ConReport'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'Contact'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CbtItemNumber', [TblParentIdFieldName]=N'CbtCustomerId' WHERE [SysRefName]=N'CustBusinessTerm'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CustItemNumber', [TblParentIdFieldName]=N'CustCustomerId' WHERE [SysRefName]=N'CustContact'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'CustDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CdcItemNumber', [TblParentIdFieldName]=N'CdcCustomerId' WHERE [SysRefName]=N'CustDcLocation'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'ClcItemNumber', [TblParentIdFieldName]=N'ClcCustDcLocationId' WHERE [SysRefName]=N'CustDcLocationContact'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CdrItemNumber', [TblParentIdFieldName]=N'CdrCustomerId' WHERE [SysRefName]=N'CustDocReference'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'FclPeriod', [TblParentIdFieldName]=N'CustId' WHERE [SysRefName]=N'CustFinancialCalendar'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CustItemNumber', [TblParentIdFieldName]=N'CustOrgId' WHERE [SysRefName]=N'Customer'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'CustReport'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'ItemNumber' WHERE [SysRefName]=N'DeliveryStatus'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'EDI'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'einInvoiceID' WHERE [SysRefName]=N'EDIInvoice'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'emdDetailID' WHERE [SysRefName]=N'EDIManifestDetail'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'emhHeaderID' WHERE [SysRefName]=N'EDIManifestHeader'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'esdHeaderID' WHERE [SysRefName]=N'EDIShipmentStatusDetail'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'eshHeaderID' WHERE [SysRefName]=N'EDIShipmentStatusHeader'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'esdDetailID' WHERE [SysRefName]=N'EDISummaryDetail'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'eshHeaderID' WHERE [SysRefName]=N'EDISummaryHeader'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'Job'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'AjbLineOrder', [TblParentIdFieldName]=N'JobID' WHERE [SysRefName]=N'JobAttribute'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CgoLineItem', [TblParentIdFieldName]=N'JobID' WHERE [SysRefName]=N'JobCargo'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'JobDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'JdrItemNumber', [TblParentIdFieldName]=N'JobID' WHERE [SysRefName]=N'JobDocReference'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'GwyGatewaySortOrder', [TblParentIdFieldName]=N'JobID' WHERE [SysRefName]=N'JobGateway'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CstLineItem', [TblParentIdFieldName]=N'JobID' WHERE [SysRefName]=N'JobRefCostSheet'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'JobRefStatus'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'JobReport'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'MenuAccessLevel'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'MenuDriver'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'MenuOptionLevel'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'MessageType'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'OrgRoleSortOrder', [TblParentIdFieldName]=N'OrgId' WHERE [SysRefName]=N'OrgActRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'SecLineOrder', [TblParentIdFieldName]=N'OrgId' WHERE [SysRefName]=N'OrgActSecurityByRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'OrgActSubSecurityByRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'OrgSortOrder' WHERE [SysRefName]=N'Organization'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CreItemNumber', [TblParentIdFieldName]=N'OrgId' WHERE [SysRefName]=N'OrgCredential'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'OrgDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'FclPeriod', [TblParentIdFieldName]=N'OrgId' WHERE [SysRefName]=N'OrgFinancialCalendar'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'MrkOrder', [TblParentIdFieldName]=N'OrgId' WHERE [SysRefName]=N'OrgMarketSupport'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PocSortOrder', [TblParentIdFieldName]=N'OrgId' WHERE [SysRefName]=N'OrgPocContact'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'OrgRoleSortOrder' WHERE [SysRefName]=N'OrgRefRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'OrgReport'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'OrgRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'OrgRolesResp'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'PrgBillableRate'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'PrgCostRate'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'PrgDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PehItemNumber', [TblParentIdFieldName]=N'PehProgramID' WHERE [SysRefName]=N'PrgEdiHeader'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'PrgEdiMapping'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'PrgMvoc'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'QueQuestionNumber', [TblParentIdFieldName]=N'MVOCID' WHERE [SysRefName]=N'PrgMvocRefQuestion'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'AttItemNumber', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'PrgRefAttributeDefault'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PgdGatewaySortOrder', [TblParentIdFieldName]=N'PgdProgramID' WHERE [SysRefName]=N'PrgRefGatewayDefault'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'PrgReport'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PrgRoleSortOrder', [TblParentIdFieldName]=N'' WHERE [SysRefName]=N'PrgRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PacApptItem', [TblParentIdFieldName]=N'PacProgramID' WHERE [SysRefName]=N'PrgShipApptmtReasonCode'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PscShipItem', [TblParentIdFieldName]=N'PscProgramID' WHERE [SysRefName]=N'PrgShipStatusReasonCode'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PvlItemNumber', [TblParentIdFieldName]=N'PvlProgramID' WHERE [SysRefName]=N'PrgVendLocation'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'Program'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblMainModuleId]=NULL, [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'PrgRoleSortOrder', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'ProgramRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'Report'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'CatalogItemNumber', [TblParentIdFieldName]=N'CatalogProgramID' WHERE [SysRefName]=N'ScrCatalogList'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'OSDID', [TblItemNumberFieldName]=N'OSDItemNumber', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'ScrOsdList'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'ReasonID', [TblItemNumberFieldName]=N'ReasonItemNumber', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'ScrOsdReasonList'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'RequirementID', [TblItemNumberFieldName]=N'RequirementLineItem', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'ScrRequirementList'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'ReturnReasonID', [TblItemNumberFieldName]=N'ReturnReasonLineItem', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'ScrReturnReasonList'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'ServiceID', [TblItemNumberFieldName]=N'ServiceLineItem', [TblParentIdFieldName]=N'ProgramID' WHERE [SysRefName]=N'ScrServiceList'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'SecLineOrder', [TblParentIdFieldName]=N'OrgRefRoleId' WHERE [SysRefName]=N'SecurityByRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'State'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'StatusLog'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'SubSecurityByRole'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'SysSetting'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'SystemAccount'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'SystemMessage'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'TabSortOrder' WHERE [SysRefName]=N'SystemPageTabName'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'SysSortOrder' WHERE [SysRefName]=N'SystemReference'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'SysRefName' WHERE [SysRefName]=N'TableReference'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'Validation'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'VbtItemNumber', [TblParentIdFieldName]=N'VbtVendorID' WHERE [SysRefName]=N'VendBusinessTerm'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'VendItemNumber', [TblParentIdFieldName]=N'VendVendorId' WHERE [SysRefName]=N'VendContact'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'VendDashboard'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'VdcItemNumber', [TblParentIdFieldName]=N'VdcVendorId' WHERE [SysRefName]=N'VendDcLocation'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'VlcItemNumber', [TblParentIdFieldName]=N'VlcVendDcLocationId' WHERE [SysRefName]=N'VendDcLocationContact'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'VdrItemNumber', [TblParentIdFieldName]=N'VdrVendorId' WHERE [SysRefName]=N'VendDocReference'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'FclPeriod', [TblParentIdFieldName]=N'VendId' WHERE [SysRefName]=N'VendFinancialCalendar'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id', [TblItemNumberFieldName]=N'VendItemNumber', [TblParentIdFieldName]=N'VendOrgId' WHERE [SysRefName]=N'Vendor'
UPDATE [dbo].[SYSTM000Ref_Table] SET [TblPrimaryKeyName]=N'Id' WHERE [SysRefName]=N'VendReport'