/*Copyright(2016) Meridian Worldwide Transportation Group
All Rights Reserved Worldwide
==========================================================================================================
Program Title:                                Meridian 4th Party Logistics(M4PL)
Programmer:                                   Akhil
Date Programmed:                              10/10/2017
Program Name:                                 UserToken
Purpose:                                      Contains objects related to UserToken
==========================================================================================================*/

namespace M4PL.Entities.Support
{
    /// <summary>
    ///     Store the User Token Generated by OAuth API client
    /// </summary>
    public class UserToken
    {
        /// <summary>
        /// Gets or sets the authentication toekn.
        /// </summary>
        /// <value>
        /// The AccessToken.
        /// </value>
        public string AccessToken { get; set; }

        /// <summary>
        /// Gets or sets the token type.
        /// </summary>
        /// <value>
        /// The TokenType.
        /// </value>
        public string TokenType { get; set; }

        /// <summary>
        /// Gets or sets the expireation time of session.
        /// </summary>
        /// <value>
        /// The ExpiresIn.
        /// </value>
        public int ExpiresIn { get; set; }

        /// <summary>
        /// Gets or sets the refreshed token
        /// </summary>
        /// <value>
        /// The RefreshToken.
        /// </value>
        public string RefreshToken { get; set; }

        /// <summary>
        /// Gets or sets the user name.
        /// </summary>
        /// <value>
        /// The UserName.
        /// </value>
        public string UserName { get; set; }
    }
}