ALTER TABLE [JOBDL000Master]
ALTER COLUMN [JobQtyOrdered] int NULL

ALTER TABLE [JOBDL000Master]
ALTER COLUMN [JobQtyActual] int NULL

ALTER TABLE [JOBDL000Master]
ALTER COLUMN [JobPartsOrdered] int NULL

ALTER TABLE [JOBDL000Master]
ALTER COLUMN [JobPartsActual] int NULL