ALTER TABLE [dbo].[JOBDL010Cargo] DROP CONSTRAINT [FK_JOBDL010Cargo_CgoPackagingTypeId_SYSTM000Ref_Options]
GO
ALTER TABLE [dbo].[JOBDL010Cargo]  WITH NOCHECK ADD  CONSTRAINT [FK_JOBDL010Cargo_CgoPackagingTypeId_SYSTM000Ref_Options] FOREIGN KEY([CgoPackagingTypeId])
REFERENCES [dbo].[SYSTM000Ref_Options] ([Id])
GO
ALTER TABLE [dbo].[JOBDL010Cargo] CHECK CONSTRAINT [FK_JOBDL010Cargo_CgoPackagingTypeId_SYSTM000Ref_Options]
GO

ALTER TABLE [dbo].[JOBDL010Cargo] DROP CONSTRAINT [FK_JOBDL010Cargo_CgoQtyUnitsId_SYSTM000Ref_Options]
GO
ALTER TABLE [dbo].[JOBDL010Cargo]  WITH NOCHECK ADD  CONSTRAINT [FK_JOBDL010Cargo_CgoQtyUnitsId_SYSTM000Ref_Options] FOREIGN KEY([CgoQtyUnitsId])
REFERENCES [dbo].[SYSTM000Ref_Options] ([Id])
GO
ALTER TABLE [dbo].[JOBDL010Cargo] CHECK CONSTRAINT [FK_JOBDL010Cargo_CgoQtyUnitsId_SYSTM000Ref_Options]
GO

ALTER TABLE [dbo].[JOBDL010Cargo] DROP CONSTRAINT [FK_JOBDL010Cargo_CgoVolumeUnitsId_SYSTM000Ref_Options]
GO
ALTER TABLE [dbo].[JOBDL010Cargo]  WITH NOCHECK ADD  CONSTRAINT [FK_JOBDL010Cargo_CgoVolumeUnitsId_SYSTM000Ref_Options] FOREIGN KEY([CgoVolumeUnitsId])
REFERENCES [dbo].[SYSTM000Ref_Options] ([Id])
GO
ALTER TABLE [dbo].[JOBDL010Cargo] CHECK CONSTRAINT [FK_JOBDL010Cargo_CgoVolumeUnitsId_SYSTM000Ref_Options]
GO

ALTER TABLE [dbo].[JOBDL010Cargo] DROP CONSTRAINT [FK_JOBDL010Cargo_CgoWeightUnitsId_SYSTM000Ref_Options]
GO
ALTER TABLE [dbo].[JOBDL010Cargo]  WITH NOCHECK ADD  CONSTRAINT [FK_JOBDL010Cargo_CgoWeightUnitsId_SYSTM000Ref_Options] FOREIGN KEY([CgoWeightUnitsId])
REFERENCES [dbo].[SYSTM000Ref_Options] ([Id])
GO
ALTER TABLE [dbo].[JOBDL010Cargo] CHECK CONSTRAINT [FK_JOBDL010Cargo_CgoWeightUnitsId_SYSTM000Ref_Options]
GO