
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Delivery POC Phone',ColCaption='Delivery POC Phone',ColGridAliasName='Delivery POC Phone' 
WHERE  ColColumnName='JobDeliverySitePOCPhone'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Origin POC Phone',ColCaption='Origin POC Phone',ColGridAliasName='Origin POC Phone' 
WHERE  ColColumnName='JobOriginSitePOCPhone'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Seller POC Phone',ColCaption='Seller POC Phone',ColGridAliasName='Seller POC Phone' 
WHERE  ColColumnName='JobSellerSitePOCPhone'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Seller POC Phone 2',ColCaption='Seller POC Phone 2',ColGridAliasName='Seller POC Phone 2' 
WHERE  ColColumnName='JobSellerSitePOCPhone2'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Delivery POC Phone 2',ColCaption='Delivery POC Phone 2',ColGridAliasName='Delivery POC Phone 2' 
WHERE  ColColumnName='JobDeliverySitePOCPhone2'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Origin POC Phone 2',ColCaption='Origin POC Phone 2',ColGridAliasName='Origin POC Phone 2' 
WHERE  ColColumnName='JobOriginSitePOCPhone2'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Ship From POC Phone',ColCaption='Ship From POC Phone',ColGridAliasName='Ship From POC Phone' 
WHERE  ColColumnName='JobShipFromSitePOCPhone'
UPDATE SYSTM000ColumnsAlias SET COLALIASNAME ='Ship From POC Phone 2',ColCaption='Ship From POC Phone 2',ColGridAliasName='Ship From POC Phone 2' 
WHERE  ColColumnName='JobShipFromSitePOCPhone2'
