/*Copyright(2016) Meridian Worldwide Transportation Group
All Rights Reserved Worldwide
==========================================================================================================
Program Title:                                Meridian 4th Party Logistics(M4PL)
Programmer:                                   Prashant Aggarwal
Date Programmed:                              10/03/2019
Program Name:                                 NavSalesOrderItem
Purpose:                                      Contains objects related to NavSalesOrderItem
==========================================================================================================*/
using System;

namespace M4PL.Entities.Finance
{
	public class NavSalesOrderItem
	{
		public string Key { get; set; }
		public ItemType Type { get; set; }
		public bool TypeSpecified { get; set; }
		public string FilteredTypeField { get; set; }
		public string No { get; set; }
		public string M4PL_Job_ID { get; set; }
		public bool Surcharge { get; set; }
		public bool SurchargeSpecified { get; set; }
		public string Cross_Reference_No { get; set; }
		public string IC_Partner_Code { get; set; }
		public IC_Partner_Ref_Type IC_Partner_Ref_Type { get; set; }

		public bool IC_Partner_Ref_TypeSpecified { get; set; }
		public string IC_Partner_Reference { get; set; }
		public string Variant_Code { get; set; }
		public bool Substitution_Available { get; set; }
		public bool Substitution_AvailableSpecified { get; set; }
		public string Purchasing_Code { get; set; }
		public bool Nonstock { get; set; }
		public bool NonstockSpecified { get; set; }
		public string VAT_Prod_Posting_Group { get; set; }
		public string Description { get; set; }
		public decimal Net_Weight { get; set; }
		public bool Net_WeightSpecified { get; set; }
		public bool Rate_Quoted { get; set; }
		public bool Rate_QuotedSpecified { get; set; }
		public bool Drop_Shipment { get; set; }
		public bool Drop_ShipmentSpecified { get; set; }
		public bool Special_Order { get; set; }
		public bool Special_OrderSpecified { get; set; }
		public string Return_Reason_Code { get; set; }
		public string Package_Tracking_No { get; set; }
		public bool ReserveSpecified { get; set; }
		public decimal Quantity { get; set; }
		public bool QuantitySpecified { get; set; }
		public decimal Qty_to_Assemble_to_Order { get; set; }
		public bool Qty_to_Assemble_to_OrderSpecified { get; set; }
		public decimal Std_Pack_Quantity { get; set; }
		public bool Std_Pack_QuantitySpecified { get; set; }
		public decimal Reserved_Quantity { get; set; }
		public bool Reserved_QuantitySpecified { get; set; }
		public string Unit_of_Measure_Code { get; set; }
		public string Std_Pack_Unit_of_Measure_Code { get; set; }
		public int Std_Packs_per_Package { get; set; }
		public bool Std_Packs_per_PackageSpecified { get; set; }
		public string Unit_of_Measure { get; set; }
		public decimal Unit_Cost_LCY { get; set; }
		public bool Unit_Cost_LCYSpecified { get; set; }
		public bool SalesPriceExist { get; set; }
		public bool SalesPriceExistSpecified { get; set; }
		public bool Unit_PriceSpecified { get; set; }
		public bool Tax_Liable { get; set; }
		public bool Tax_LiableSpecified { get; set; }
		public string Tax_Area_Code { get; set; }
		public string Tax_Group_Code { get; set; }
		public decimal Line_Discount_Percent { get; set; }
		public bool Line_Discount_PercentSpecified { get; set; }
		public decimal Line_Amount { get; set; }
		public bool Line_AmountSpecified { get; set; }
		public decimal Amount_Including_VAT { get; set; }
		public bool Amount_Including_VATSpecified { get; set; }
		public bool SalesLineDiscExistsSpecified { get; set; }
		public decimal Line_Discount_Amount { get; set; }
		public bool Line_Discount_AmountSpecified { get; set; }
		public decimal Prepayment_Percent { get; set; }
		public bool Prepayment_PercentSpecified { get; set; }
		public decimal Prepmt_Line_Amount { get; set; }
		public bool Prepmt_Line_AmountSpecified { get; set; }
		public decimal Prepmt_Amt_Inv { get; set; }
		public bool Prepmt_Amt_InvSpecified { get; set; }
		public bool Allow_Invoice_Disc { get; set; }
		public bool Allow_Invoice_DiscSpecified { get; set; }
		public decimal Inv_Discount_Amount { get; set; }
		public bool Inv_Discount_AmountSpecified { get; set; }
		public decimal Inv_Disc_Amount_to_Invoice { get; set; }
		public bool Inv_Disc_Amount_to_InvoiceSpecified { get; set; }
		public decimal Qty_to_Ship { get; set; }
		public bool Qty_to_ShipSpecified { get; set; }
		public decimal Std_Pack_Qty_to_Ship { get; set; }
		public bool Std_Pack_Qty_to_ShipSpecified { get; set; }
		public decimal Package_Qty_to_Ship { get; set; }
		public bool Package_Qty_to_ShipSpecified { get; set; }
		public decimal Quantity_Shipped { get; set; }
		public bool Quantity_ShippedSpecified { get; set; }
		public decimal Qty_to_Invoice { get; set; }
		public bool Qty_to_InvoiceSpecified { get; set; }
		public decimal Quantity_Invoiced { get; set; }
		public bool Quantity_InvoicedSpecified { get; set; }
		public decimal Prepmt_Amt_to_Deduct { get; set; }
		public bool Prepmt_Amt_to_DeductSpecified { get; set; }
		public decimal Prepmt_Amt_Deducted { get; set; }
		public bool Prepmt_Amt_DeductedSpecified { get; set; }
		public bool Allow_Item_Charge_Assignment { get; set; }
		public bool Allow_Item_Charge_AssignmentSpecified { get; set; }
		public bool Qty_to_AssignSpecified { get; set; }
		public decimal Qty_Assigned { get; set; }
		public bool Qty_AssignedSpecified { get; set; }
		public string Requested_Delivery_Date { get; set; }
		public bool Requested_Delivery_DateSpecified { get; set; }
		public string Promised_Delivery_Date { get; set; }
		public bool Promised_Delivery_DateSpecified { get; set; }
		public string Planned_Delivery_Date { get; set; }
		public bool Planned_Delivery_DateSpecified { get; set; }
		public string Planned_Shipment_Date { get; set; }
		public bool Planned_Shipment_DateSpecified { get; set; }
		public string Shipment_Date { get; set; }
		public bool Shipment_DateSpecified { get; set; }
		public string Shipping_Agent_Code { get; set; }
		public string Shipping_Agent_Service_Code { get; set; }
		public string Shipping_Time { get; set; }
		public string Work_Type_Code { get; set; }
		public decimal Whse_Outstanding_Qty { get; set; }
		public bool Whse_Outstanding_QtySpecified { get; set; }
		public decimal Whse_Outstanding_Qty_Base { get; set; }
		public bool Whse_Outstanding_Qty_BaseSpecified { get; set; }
		public decimal ATO_Whse_Outstanding_Qty { get; set; }
		public bool ATO_Whse_Outstanding_QtySpecified { get; set; }
		public decimal ATO_Whse_Outstd_Qty_Base { get; set; }
		public bool ATO_Whse_Outstd_Qty_BaseSpecified { get; set; }
		public string Outbound_Whse_Handling_Time { get; set; }
		public string Blanket_Order_No { get; set; }
		public int Blanket_Order_Line_No { get; set; }
		public bool Blanket_Order_Line_NoSpecified { get; set; }
		public string FA_Posting_Date { get; set; }
		public bool FA_Posting_DateSpecified { get; set; }
		public bool Depr_until_FA_Posting_Date { get; set; }
		public bool Depr_until_FA_Posting_DateSpecified { get; set; }
		public string Depreciation_Book_Code { get; set; }
		public bool Use_Duplication_List { get; set; }
		public bool Use_Duplication_ListSpecified { get; set; }
		public string Duplicate_in_Depreciation_Book { get; set; }
		public bool Appl_from_Item_EntrySpecified { get; set; }
		public bool Appl_to_Item_EntrySpecified { get; set; }
		public string Deferral_Code { get; set; }
		public string Shortcut_Dimension_1_Code { get; set; }
		public string Shortcut_Dimension_2_Code { get; set; }
		public string ShortcutDimCode3 { get; set; }
		public string ShortcutDimCode4 { get; set; }
		public string ShortcutDimCode5 { get; set; }
		public string ShortcutDimCode6 { get; set; }
		public string ShortcutDimCode7 { get; set; }
		public string ShortcutDimCode8 { get; set; }
		public string Document_No { get; set; }
		public int Line_No { get; set; }
		public bool Line_NoSpecified { get; set; }
		public string Required_Shipping_Agent_Code { get; set; }
		public string Required_E_Ship_Agent_Service { get; set; }
		public bool Allow_Other_Ship_Agent_Serv { get; set; }
		public bool Allow_Other_Ship_Agent_ServSpecified { get; set; }
		public bool EDI_Ship_Confirmed { get; set; }
		public bool EDI_Ship_ConfirmedSpecified { get; set; }
		public string EDI_Item_Cross_Ref { get; set; }
		public string EDI_Unit_of_Measure { get; set; }
		public decimal EDI_Unit_Price { get; set; }
		public bool EDI_Unit_PriceSpecified { get; set; }
		public bool EDI_Price_Discrepancy { get; set; }
		public bool EDI_Price_DiscrepancySpecified { get; set; }
		public int EDI_Segment_Group { get; set; }
		public bool EDI_Segment_GroupSpecified { get; set; }
		public decimal EDI_Original_Qty { get; set; }
		public bool EDI_Original_QtySpecified { get; set; }
		public bool EDI_Status_Pending { get; set; }
		public string EDI_ID { get; set; }
		public string EDI_Variant_Code { get; set; }
		public string EDI_Time { get; set; }
		public bool EDI_TimeSpecified { get; set; }
		public string EDI_DateTime { get; set; }
		public bool EDI_DateTimeSpecified { get; set; }
		public string EDI_Ship_Req_Date { get; set; }
		public bool EDI_Ship_Req_DateSpecified { get; set; }
		public EDI_Line_Type EDI_Line_Type { get; set; }
		public bool EDI_Line_TypeSpecified { get; set; }
		public EDI_Line_Status EDI_Line_Status { get; set; }
		public bool EDI_Line_StatusSpecified { get; set; }
		public string EDI_Code { get; set; }
		public decimal TotalSalesLine_Line_Amount { get; set; }
		public bool TotalSalesLine_Line_AmountSpecified { get; set; }
		public decimal Invoice_Discount_Amount { get; set; }
		public bool Invoice_Discount_AmountSpecified { get; set; }
		public decimal Invoice_Disc_Pct { get; set; }
		public bool Invoice_Disc_PctSpecified { get; set; }
		public decimal Total_Amount_Excl_VAT { get; set; }
		public bool Total_Amount_Excl_VATSpecified { get; set; }
		public decimal Total_VAT_Amount { get; set; }
		public bool Total_VAT_AmountSpecified { get; set; }
		public decimal Total_Amount_Incl_VAT { get; set; }
		public bool Total_Amount_Incl_VATSpecified { get; set; }
	}
}
