/*Copyright(2016) Meridian Worldwide Transportation Group
All Rights Reserved Worldwide
==========================================================================================================
Program Title:                                Meridian 4th Party Logistics(M4PL)
Programmer:                                   Prashant Aggarwal
Date Programmed:                              10/03/2019
Program Name:                                 NavSalesOrder
Purpose:                                      Contains objects related to PurchaseOrderItem
==========================================================================================================*/

namespace M4PL.Entities.Finance
{
	public class PurchaseOrderItem
	{
		public string No { get; set; }
		public string M4PL_Job_ID { get; set; }
		public string Cross_Reference_No { get; set; }
		public string IC_Partner_Code { get; set; }
		public IC_Partner_Ref_Type IC_Partner_Ref_Type { get; set; }
		public bool IC_Partner_Ref_TypeSpecified { get; set; }
		public string IC_Partner_Reference { get; set; }
		public string Variant_Code { get; set; }
		public bool Nonstock { get; set; }
		public bool NonstockSpecified { get; set; }
		public GST_HST GST_HST { get; set; }
		public bool GST_HSTSpecified { get; set; }
		public string VAT_Prod_Posting_Group { get; set; }
		public string Description { get; set; }
		public bool Drop_Shipment { get; set; }
		public bool Drop_ShipmentSpecified { get; set; }
		public string Return_Reason_Code { get; set; }
		public string Location_Code { get; set; }
		public string Bin_Code { get; set; }
		public decimal Quantity { get; set; }
		public bool QuantitySpecified { get; set; }
		public decimal Reserved_Quantity { get; set; }
		public bool Reserved_QuantitySpecified { get; set; }
		public decimal Job_Remaining_Qty { get; set; }
		public bool Job_Remaining_QtySpecified { get; set; }
		public string Unit_of_Measure_Code { get; set; }
		public string Unit_of_Measure { get; set; }
		public decimal Direct_Unit_Cost { get; set; }
		public bool Direct_Unit_CostSpecified { get; set; }
		public decimal Indirect_Cost_Percent { get; set; }
		public bool Indirect_Cost_PercentSpecified { get; set; }
		public bool Unit_Cost_LCYSpecified { get; set; }
		public decimal Unit_Price_LCY { get; set; }
		public bool Unit_Price_LCYSpecified { get; set; }
		public bool Tax_Liable { get; set; }
		public bool Tax_LiableSpecified { get; set; }
		public string Tax_Area_Code { get; set; }
		public string Provincial_Tax_Area_Code { get; set; }
		public string Tax_Group_Code { get; set; }
		public bool Use_Tax { get; set; }
		public bool Use_TaxSpecified { get; set; }
		public decimal Line_Discount_Percent { get; set; }
		public bool Line_Discount_PercentSpecified { get; set; }
		public decimal Line_Amount { get; set; }
		public bool Line_AmountSpecified { get; set; }
		public decimal Line_Discount_Amount { get; set; }
		public bool Line_Discount_AmountSpecified { get; set; }
		public decimal Prepayment_Percent { get; set; }
		public bool Prepayment_PercentSpecified { get; set; }
		public decimal Prepmt_Line_Amount { get; set; }
		public bool Prepmt_Line_AmountSpecified { get; set; }
		public decimal Prepmt_Amt_Inv { get; set; }
		public bool Prepmt_Amt_InvSpecified { get; set; }
		public bool Allow_Invoice_Disc { get; set; }
		public bool Allow_Invoice_DiscSpecified { get; set; }
		public decimal Inv_Discount_Amount { get; set; }
		public bool Inv_Discount_AmountSpecified { get; set; }
		public decimal Inv_Disc_Amount_to_Invoice { get; set; }
		public bool Inv_Disc_Amount_to_InvoiceSpecified { get; set; }
		public decimal Qty_to_Receive { get; set; }
		public bool Qty_to_ReceiveSpecified { get; set; }
		public decimal Quantity_Received { get; set; }
		public bool Quantity_ReceivedSpecified { get; set; }
		public decimal Qty_to_Invoice { get; set; }
		public bool Qty_to_InvoiceSpecified { get; set; }
		public decimal Quantity_Invoiced { get; set; }
		public bool Quantity_InvoicedSpecified { get; set; }
		public decimal Prepmt_Amt_to_Deduct { get; set; }
		public bool Prepmt_Amt_to_DeductSpecified { get; set; }
		public decimal Prepmt_Amt_Deducted { get; set; }
		public bool Prepmt_Amt_DeductedSpecified { get; set; }
		public bool Allow_Item_Charge_Assignment { get; set; }
		public bool Allow_Item_Charge_AssignmentSpecified { get; set; }
		public decimal Qty_to_Assign { get; set; }
		public bool Qty_to_AssignSpecified { get; set; }
		public decimal Qty_Assigned { get; set; }
		public bool Qty_AssignedSpecified { get; set; }
		public string Job_No { get; set; }
		public string Job_Task_No { get; set; }
		public int Job_Planning_Line_No { get; set; }
		public bool Job_Planning_Line_NoSpecified { get; set; }
		public Job_Line_Type Job_Line_Type { get; set; }
		public bool Job_Line_TypeSpecified { get; set; }
		public decimal Job_Unit_Price { get; set; }
		public bool Job_Unit_PriceSpecified { get; set; }
		public decimal Job_Line_Amount { get; set; }
		public bool Job_Line_AmountSpecified { get; set; }
		public decimal Job_Line_Discount_Amount { get; set; }
		public bool Job_Line_Discount_AmountSpecified { get; set; }
		public decimal Job_Line_Discount_Percent { get; set; }
		public bool Job_Line_Discount_PercentSpecified { get; set; }
		public decimal Job_Total_Price { get; set; }
		public bool Job_Total_PriceSpecified { get; set; }
		public decimal Job_Unit_Price_LCY { get; set; }
		public bool Job_Unit_Price_LCYSpecified { get; set; }
		public decimal Job_Total_Price_LCY { get; set; }
		public bool Job_Total_Price_LCYSpecified { get; set; }
		public decimal Job_Line_Amount_LCY { get; set; }
		public bool Job_Line_Amount_LCYSpecified { get; set; }
		public decimal Job_Line_Disc_Amount_LCY { get; set; }
		public bool Job_Line_Disc_Amount_LCYSpecified { get; set; }
		public string Requested_Receipt_Date { get; set; }
		public bool Requested_Receipt_DateSpecified { get; set; }
		public string Promised_Receipt_Date { get; set; }
		public bool Promised_Receipt_DateSpecified { get; set; }
		public string Planned_Receipt_Date { get; set; }
		public bool Planned_Receipt_DateSpecified { get; set; }
		public string Expected_Receipt_Date { get; set; }
		public bool Expected_Receipt_DateSpecified { get; set; }
		public string Order_Date { get; set; }
		public bool Order_DateSpecified { get; set; }
		public string Lead_Time_Calculation { get; set; }
		public Planning_Flexibility Planning_Flexibility { get; set; }
		public bool Planning_FlexibilitySpecified { get; set; }
		public string Prod_Order_No { get; set; }
		public int Prod_Order_Line_No { get; set; }
		public bool Prod_Order_Line_NoSpecified { get; set; }
		public string Operation_No { get; set; }
		public string Work_Center_No { get; set; }
		public bool Finished { get; set; }
		public bool FinishedSpecified { get; set; }
		public decimal Whse_Outstanding_Qty_Base { get; set; }
		public bool Whse_Outstanding_Qty_BaseSpecified { get; set; }
		public string Inbound_Whse_Handling_Time { get; set; }
		public string Blanket_Order_No { get; set; }
		public int Blanket_Order_Line_No { get; set; }
		public bool Blanket_Order_Line_NoSpecified { get; set; }
		public int Appl_to_Item_Entry { get; set; }
		public bool Appl_to_Item_EntrySpecified { get; set; }
		public string Deferral_Code { get; set; }
		public string Shortcut_Dimension_1_Code { get; set; }
		public string Shortcut_Dimension_2_Code { get; set; }
		public string ShortcutDimCode3 { get; set; }
		public string ShortcutDimCode4 { get; set; }
		public string ShortcutDimCode5 { get; set; }
		public string ShortcutDimCode6 { get; set; }
		public string ShortcutDimCode7 { get; set; }
		public string ShortcutDimCode8 { get; set; }
		public bool IRS_1099_Liable { get; set; }
		public bool IRS_1099_LiableSpecified { get; set; }
		public string Document_No { get; set; }
		public int Line_No { get; set; }
		public bool Line_NoSpecified { get; set; }
		public bool Over_Receive { get; set; }
		public bool Over_ReceiveSpecified { get; set; }
		public bool Over_Receive_Verified { get; set; }
		public bool Over_Receive_VerifiedSpecified { get; set; }
		public decimal EDI_Unit_Cost { get; set; }
		public bool EDI_Unit_CostSpecified { get; set; }
		public bool EDI_Cost_Discrepancy { get; set; }
		public bool EDI_Cost_DiscrepancySpecified { get; set; }
		public int EDI_Segment_Group { get; set; }
		public bool EDI_Segment_GroupSpecified { get; set; }
		public decimal Invoice_Discount_Amount { get; set; }
		public bool Invoice_Discount_AmountSpecified { get; set; }
		public decimal Invoice_Disc_Pct { get; set; }
		public bool Invoice_Disc_PctSpecified { get; set; }
		public decimal Total_Amount_Excl_VAT { get; set; }
		public bool Total_Amount_Excl_VATSpecified { get; set; }
		public decimal Total_VAT_Amount { get; set; }
		public bool Total_VAT_AmountSpecified { get; set; }
		public decimal Total_Amount_Incl_VAT { get; set; }
		public bool Total_Amount_Incl_VATSpecified { get; set; }
		public string RefreshTotals { get; set; }
	}
}
