
INSERT INTO [dbo].[SYSTM000ColumnsAlias]
           ([LangCode]
           ,[ColTableName]
           ,[ColAssociatedTableName]
           ,[ColColumnName]
           ,[ColAliasName]
           ,[ColCaption]
           ,[ColLookupId]
           ,[ColLookupCode]
           ,[ColDescription]
           ,[ColSortOrder]
           ,[ColIsReadOnly]
           ,[ColIsVisible]
           ,[ColIsDefault]
           ,[StatusId]
           ,[ColDisplayFormat]
           ,[ColAllowNegativeValue]
           ,[ColIsGroupBy]
           ,[ColMask]
           ,[IsGridColumn]
           ,[ColGridAliasName])
     VALUES
           ('EN'
           ,'JobGateway'
           ,null
           ,'GwyGatewayText'
           ,'Comments'
           ,'Comments'
           ,null
           ,null
           ,null
           ,56
           ,0
           ,0
           ,1
           ,1
           ,null
           ,0
           ,0
           ,null
           ,0
           ,'Comments')
GO



INSERT INTO [dbo].[SYSTM000ColumnsAlias]
           ([LangCode]
           ,[ColTableName]
           ,[ColAssociatedTableName]
           ,[ColColumnName]
           ,[ColAliasName]
           ,[ColCaption]
           ,[ColLookupId]
           ,[ColLookupCode]
           ,[ColDescription]
           ,[ColSortOrder]
           ,[ColIsReadOnly]
           ,[ColIsVisible]
           ,[ColIsDefault]
           ,[StatusId]
           ,[ColDisplayFormat]
           ,[ColAllowNegativeValue]
           ,[ColIsGroupBy]
           ,[ColMask]
           ,[IsGridColumn]
           ,[ColGridAliasName])
     VALUES
           ('EN'
           ,'Job'
           ,null
           ,'JobDeliveryCommentText'
           ,'Notes'
           ,'Notes'
           ,null
           ,null
           ,null
           ,143
           ,0
           ,1
           ,1
           ,1
           ,null
           ,0
           ,0
           ,null
           ,0
           ,'Notes')
GO


