IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einFuelSurchargeQty')
BEGIN
   ALTER TABLE EDI210Invoice ADD einFuelSurchargeQty INT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAdditionalHandlingQty')
BEGIN
   ALTER TABLE EDI210Invoice ADD einAdditionalHandlingQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einCabinetReturnQty')
BEGIN
   ALTER TABLE EDI210Invoice ADD einCabinetReturnQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einGoodSalesTaxQty')
BEGIN
   ALTER TABLE EDI210Invoice ADD einGoodSalesTaxQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einHarmonizedServiceTaxQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einHarmonizedServiceTaxQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einInsideDeliveryQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einInsideDeliveryQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einMinimumChargeQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einMinimumChargeQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einOutOfRangeMilesQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einOutOfRangeMilesQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einPickupChargeQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einPickupChargeQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einReconsignmentQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einReconsignmentQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einRedeliveryAttemptQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einRedeliveryAttemptQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einHolidayOrWeekendDeliveryQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einHolidayOrWeekendDeliveryQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einSpecialDeliveryQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einSpecialDeliveryQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einStairsExcessDeliveryQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einStairsExcessDeliveryQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einStorageQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einStorageQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einStanisciHandlingQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einStanisciHandlingQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einUnloadingFeeQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einUnloadingFeeQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einBridgeTollQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einBridgeTollQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einExtraLaborQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einExtraLaborQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einHighwayTollQty')
BEGIN
ALTER TABLE EDI210Invoice ADD einHighwayTollQty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial1Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial1Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial2Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial2Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial3Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial3Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial4Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial4Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial5Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial5Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial6Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial6Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial7Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial7Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial8Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial8Qty INT
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial9Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial9Qty INT
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EDI210Invoice' AND COLUMN_NAME = 'einAccessorial10Qty')
BEGIN
ALTER TABLE EDI210Invoice ADD einAccessorial10Qty INT
END
