  WITH SYSTM000COLUMNSALIAS_CTE  AS (
    SELECT  ROW_NUMBER() OVER(PARTITION BY [COLALIASNAME] ORDER BY ID DESC) AS ROWNUMBER  FROM  [SYSTM000COLUMNSALIAS] WHERE COLTABLENAME = 'JOBCARGO' )
  DELETE FROM SYSTM000COLUMNSALIAS_CTE WHERE  ROWNUMBER >1
  
  
  
